// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/adblock_engine.dart';
import 'api/downloader.dart';
import 'api/extractor.dart';
import 'api/models.dart';
import 'api/process_helper.dart';
import 'api/remote_rules.dart';
import 'api/security.dart';
import 'api/simple.dart';
import 'api/stream_policy.dart';
import 'api/universal_extractor.dart';
import 'api/video_processor.dart';
import 'api/ytdlp_wrapper.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -937995543;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'rust_lib_dark_downloader',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiDownloaderCancelJob({required String jobId});

  Future<void> crateApiVideoProcessorCompressVideo(
      {required String inputPath,
      required String outputPath,
      required String ffmpegPath});

  Future<void> crateApiVideoProcessorConvertToMp3(
      {required String inputPath,
      required String outputPath,
      required String ffmpegPath});

  Future<void> crateApiVideoProcessorConvertToMp3Rich(
      {required String inputPath,
      required String outputPath,
      required String ffmpegPath,
      String? title,
      String? artist,
      String? album,
      String? date,
      String? comment,
      String? coverPath});

  Future<DownloadResult> crateApiDownloaderDownloadFile(
      {required String url, required String outputPath});

  Future<DownloadResult> crateApiDownloaderDownloadFileV2(
      {required String url,
      required String outputPath,
      String? audioUrl,
      required String jobId,
      required int connections,
      String? muxFfmpeg});

  Future<void> crateApiVideoProcessorEmbedAlbumArt(
      {required String mp3Path,
      required String coverPath,
      required String ffmpegPath});

  Future<ExtractionResult> crateApiExtractorExtract({required String url});

  Future<void> crateApiVideoProcessorExtractAudio(
      {required String videoPath,
      required String outputPath,
      required String ffmpegPath});

  Future<VideoInfoResult> crateApiYtdlpWrapperExtractAudioViaYtdlp(
      {required String url});

  Future<PlaylistResult> crateApiYtdlpWrapperExtractPlaylistViaYtdlp(
      {required String url});

  Future<VideoInfoResult> crateApiUniversalExtractorExtractUltra(
      {required String url});

  Future<VideoInfoResult> crateApiRemoteRulesExtractViaRules(
      {required String url});

  Future<VideoInfoResult> crateApiYtdlpWrapperExtractViaYtdlp(
      {required String url});

  Future<VideoInfoResult> crateApiExtractorExtractWithOptions(
      {required String url, required bool bypassBlocks});

  Future<String> crateApiDownloaderGetDownloadsDir();

  Future<DownloadProgressSnapshot?> crateApiDownloaderGetJobProgress(
      {required String jobId});

  Future<String?> crateApiRemoteRulesGetRemotePattern(
      {required String platform, required String key});

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  bool crateApiYtdlpWrapperIsYtdlpAvailable();

  Future<void> crateApiVideoProcessorMuxVideoAudio(
      {required String videoPath,
      required String audioPath,
      required String outputPath,
      required String ffmpegPath});

  Future<PlatformRule> crateApiRemoteRulesPlatformRuleDefault();

  Future<RulesRegistry> crateApiRemoteRulesRulesRegistryDefault();

  Future<bool> crateApiSecurityRustCheckAppIntegrity();

  Future<String> crateApiSecurityRustGenerateSecureToken(
      {required String payload});

  List<String> crateApiAdblockEngineRustGetDefaultAdRules();

  Future<String> crateApiSecurityRustGetDeviceFingerprint();

  String crateApiRemoteRulesRustGetRulesStatus();

  Future<SupabaseSecrets> crateApiSecurityRustGetSupabaseConfig();

  void crateApiAdblockEngineRustInitAdblocker({required List<String> rules});

  Future<int> crateApiRemoteRulesRustInstallBundledRules(
      {required String json});

  bool crateApiAdblockEngineRustShouldBlockUrl({required String url});

  Future<String> crateApiSecurityRustSignMessage(
      {required String message, required String secret});

  Future<void> crateApiRemoteRulesRustSyncRemoteRules({required String url});

  Future<String> crateApiDownloaderSafeFilename(
      {required String title, required String format});

  void crateApiYtdlpWrapperSetCookiesPath({required String path});

  void crateApiYtdlpWrapperSetProxyUrl({required String url});

  void crateApiYtdlpWrapperSetYtdlpBinaryPath({required String path});

  Future<bool> crateApiStreamPolicyShouldPairSeparateAudio(
      {required bool isVideoOnly, required bool separateAudioTracksAvailable});

  Future<void> crateApiSecurityVaultDecryptFile(
      {required String vaultPath,
      required String outputPath,
      required String password});

  Future<void> crateApiSecurityVaultEncryptFile(
      {required String sourcePath,
      required String targetPath,
      required String password});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiDownloaderCancelJob({required String jobId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(jobId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDownloaderCancelJobConstMeta,
      argValues: [jobId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDownloaderCancelJobConstMeta =>
      const TaskConstMeta(
        debugName: "cancel_job",
        argNames: ["jobId"],
      );

  @override
  Future<void> crateApiVideoProcessorCompressVideo(
      {required String inputPath,
      required String outputPath,
      required String ffmpegPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(inputPath, serializer);
        sse_encode_String(outputPath, serializer);
        sse_encode_String(ffmpegPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiVideoProcessorCompressVideoConstMeta,
      argValues: [inputPath, outputPath, ffmpegPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiVideoProcessorCompressVideoConstMeta =>
      const TaskConstMeta(
        debugName: "compress_video",
        argNames: ["inputPath", "outputPath", "ffmpegPath"],
      );

  @override
  Future<void> crateApiVideoProcessorConvertToMp3(
      {required String inputPath,
      required String outputPath,
      required String ffmpegPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(inputPath, serializer);
        sse_encode_String(outputPath, serializer);
        sse_encode_String(ffmpegPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiVideoProcessorConvertToMp3ConstMeta,
      argValues: [inputPath, outputPath, ffmpegPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiVideoProcessorConvertToMp3ConstMeta =>
      const TaskConstMeta(
        debugName: "convert_to_mp3",
        argNames: ["inputPath", "outputPath", "ffmpegPath"],
      );

  @override
  Future<void> crateApiVideoProcessorConvertToMp3Rich(
      {required String inputPath,
      required String outputPath,
      required String ffmpegPath,
      String? title,
      String? artist,
      String? album,
      String? date,
      String? comment,
      String? coverPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(inputPath, serializer);
        sse_encode_String(outputPath, serializer);
        sse_encode_String(ffmpegPath, serializer);
        sse_encode_opt_String(title, serializer);
        sse_encode_opt_String(artist, serializer);
        sse_encode_opt_String(album, serializer);
        sse_encode_opt_String(date, serializer);
        sse_encode_opt_String(comment, serializer);
        sse_encode_opt_String(coverPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiVideoProcessorConvertToMp3RichConstMeta,
      argValues: [
        inputPath,
        outputPath,
        ffmpegPath,
        title,
        artist,
        album,
        date,
        comment,
        coverPath
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiVideoProcessorConvertToMp3RichConstMeta =>
      const TaskConstMeta(
        debugName: "convert_to_mp3_rich",
        argNames: [
          "inputPath",
          "outputPath",
          "ffmpegPath",
          "title",
          "artist",
          "album",
          "date",
          "comment",
          "coverPath"
        ],
      );

  @override
  Future<DownloadResult> crateApiDownloaderDownloadFile(
      {required String url, required String outputPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(url, serializer);
        sse_encode_String(outputPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_download_result,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDownloaderDownloadFileConstMeta,
      argValues: [url, outputPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDownloaderDownloadFileConstMeta =>
      const TaskConstMeta(
        debugName: "download_file",
        argNames: ["url", "outputPath"],
      );

  @override
  Future<DownloadResult> crateApiDownloaderDownloadFileV2(
      {required String url,
      required String outputPath,
      String? audioUrl,
      required String jobId,
      required int connections,
      String? muxFfmpeg}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(url, serializer);
        sse_encode_String(outputPath, serializer);
        sse_encode_opt_String(audioUrl, serializer);
        sse_encode_String(jobId, serializer);
        sse_encode_u_32(connections, serializer);
        sse_encode_opt_String(muxFfmpeg, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_download_result,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDownloaderDownloadFileV2ConstMeta,
      argValues: [url, outputPath, audioUrl, jobId, connections, muxFfmpeg],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDownloaderDownloadFileV2ConstMeta =>
      const TaskConstMeta(
        debugName: "download_file_v2",
        argNames: [
          "url",
          "outputPath",
          "audioUrl",
          "jobId",
          "connections",
          "muxFfmpeg"
        ],
      );

  @override
  Future<void> crateApiVideoProcessorEmbedAlbumArt(
      {required String mp3Path,
      required String coverPath,
      required String ffmpegPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(mp3Path, serializer);
        sse_encode_String(coverPath, serializer);
        sse_encode_String(ffmpegPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiVideoProcessorEmbedAlbumArtConstMeta,
      argValues: [mp3Path, coverPath, ffmpegPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiVideoProcessorEmbedAlbumArtConstMeta =>
      const TaskConstMeta(
        debugName: "embed_album_art",
        argNames: ["mp3Path", "coverPath", "ffmpegPath"],
      );

  @override
  Future<ExtractionResult> crateApiExtractorExtract({required String url}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(url, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_extraction_result,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiExtractorExtractConstMeta,
      argValues: [url],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiExtractorExtractConstMeta => const TaskConstMeta(
        debugName: "extract",
        argNames: ["url"],
      );

  @override
  Future<void> crateApiVideoProcessorExtractAudio(
      {required String videoPath,
      required String outputPath,
      required String ffmpegPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(videoPath, serializer);
        sse_encode_String(outputPath, serializer);
        sse_encode_String(ffmpegPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiVideoProcessorExtractAudioConstMeta,
      argValues: [videoPath, outputPath, ffmpegPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiVideoProcessorExtractAudioConstMeta =>
      const TaskConstMeta(
        debugName: "extract_audio",
        argNames: ["videoPath", "outputPath", "ffmpegPath"],
      );

  @override
  Future<VideoInfoResult> crateApiYtdlpWrapperExtractAudioViaYtdlp(
      {required String url}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(url, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_video_info_result,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiYtdlpWrapperExtractAudioViaYtdlpConstMeta,
      argValues: [url],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiYtdlpWrapperExtractAudioViaYtdlpConstMeta =>
      const TaskConstMeta(
        debugName: "extract_audio_via_ytdlp",
        argNames: ["url"],
      );

  @override
  Future<PlaylistResult> crateApiYtdlpWrapperExtractPlaylistViaYtdlp(
      {required String url}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(url, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_playlist_result,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiYtdlpWrapperExtractPlaylistViaYtdlpConstMeta,
      argValues: [url],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiYtdlpWrapperExtractPlaylistViaYtdlpConstMeta =>
      const TaskConstMeta(
        debugName: "extract_playlist_via_ytdlp",
        argNames: ["url"],
      );

  @override
  Future<VideoInfoResult> crateApiUniversalExtractorExtractUltra(
      {required String url}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(url, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_video_info_result,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiUniversalExtractorExtractUltraConstMeta,
      argValues: [url],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiUniversalExtractorExtractUltraConstMeta =>
      const TaskConstMeta(
        debugName: "extract_ultra",
        argNames: ["url"],
      );

  @override
  Future<VideoInfoResult> crateApiRemoteRulesExtractViaRules(
      {required String url}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(url, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_video_info_result,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiRemoteRulesExtractViaRulesConstMeta,
      argValues: [url],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiRemoteRulesExtractViaRulesConstMeta =>
      const TaskConstMeta(
        debugName: "extract_via_rules",
        argNames: ["url"],
      );

  @override
  Future<VideoInfoResult> crateApiYtdlpWrapperExtractViaYtdlp(
      {required String url}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(url, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_video_info_result,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiYtdlpWrapperExtractViaYtdlpConstMeta,
      argValues: [url],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiYtdlpWrapperExtractViaYtdlpConstMeta =>
      const TaskConstMeta(
        debugName: "extract_via_ytdlp",
        argNames: ["url"],
      );

  @override
  Future<VideoInfoResult> crateApiExtractorExtractWithOptions(
      {required String url, required bool bypassBlocks}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(url, serializer);
        sse_encode_bool(bypassBlocks, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_video_info_result,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiExtractorExtractWithOptionsConstMeta,
      argValues: [url, bypassBlocks],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiExtractorExtractWithOptionsConstMeta =>
      const TaskConstMeta(
        debugName: "extract_with_options",
        argNames: ["url", "bypassBlocks"],
      );

  @override
  Future<String> crateApiDownloaderGetDownloadsDir() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDownloaderGetDownloadsDirConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDownloaderGetDownloadsDirConstMeta =>
      const TaskConstMeta(
        debugName: "get_downloads_dir",
        argNames: [],
      );

  @override
  Future<DownloadProgressSnapshot?> crateApiDownloaderGetJobProgress(
      {required String jobId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(jobId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 18, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_opt_box_autoadd_download_progress_snapshot,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDownloaderGetJobProgressConstMeta,
      argValues: [jobId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDownloaderGetJobProgressConstMeta =>
      const TaskConstMeta(
        debugName: "get_job_progress",
        argNames: ["jobId"],
      );

  @override
  Future<String?> crateApiRemoteRulesGetRemotePattern(
      {required String platform, required String key}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(platform, serializer);
        sse_encode_String(key, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 19, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiRemoteRulesGetRemotePatternConstMeta,
      argValues: [platform, key],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiRemoteRulesGetRemotePatternConstMeta =>
      const TaskConstMeta(
        debugName: "get_remote_pattern",
        argNames: ["platform", "key"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleGreetConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta => const TaskConstMeta(
        debugName: "greet",
        argNames: ["name"],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 21, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  @override
  bool crateApiYtdlpWrapperIsYtdlpAvailable() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiYtdlpWrapperIsYtdlpAvailableConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiYtdlpWrapperIsYtdlpAvailableConstMeta =>
      const TaskConstMeta(
        debugName: "is_ytdlp_available",
        argNames: [],
      );

  @override
  Future<void> crateApiVideoProcessorMuxVideoAudio(
      {required String videoPath,
      required String audioPath,
      required String outputPath,
      required String ffmpegPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(videoPath, serializer);
        sse_encode_String(audioPath, serializer);
        sse_encode_String(outputPath, serializer);
        sse_encode_String(ffmpegPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 23, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiVideoProcessorMuxVideoAudioConstMeta,
      argValues: [videoPath, audioPath, outputPath, ffmpegPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiVideoProcessorMuxVideoAudioConstMeta =>
      const TaskConstMeta(
        debugName: "mux_video_audio",
        argNames: ["videoPath", "audioPath", "outputPath", "ffmpegPath"],
      );

  @override
  Future<PlatformRule> crateApiRemoteRulesPlatformRuleDefault() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 24, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_platform_rule,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiRemoteRulesPlatformRuleDefaultConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiRemoteRulesPlatformRuleDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "platform_rule_default",
        argNames: [],
      );

  @override
  Future<RulesRegistry> crateApiRemoteRulesRulesRegistryDefault() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 25, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_rules_registry,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiRemoteRulesRulesRegistryDefaultConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiRemoteRulesRulesRegistryDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "rules_registry_default",
        argNames: [],
      );

  @override
  Future<bool> crateApiSecurityRustCheckAppIntegrity() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 26, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSecurityRustCheckAppIntegrityConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSecurityRustCheckAppIntegrityConstMeta =>
      const TaskConstMeta(
        debugName: "rust_check_app_integrity",
        argNames: [],
      );

  @override
  Future<String> crateApiSecurityRustGenerateSecureToken(
      {required String payload}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(payload, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 27, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSecurityRustGenerateSecureTokenConstMeta,
      argValues: [payload],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSecurityRustGenerateSecureTokenConstMeta =>
      const TaskConstMeta(
        debugName: "rust_generate_secure_token",
        argNames: ["payload"],
      );

  @override
  List<String> crateApiAdblockEngineRustGetDefaultAdRules() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiAdblockEngineRustGetDefaultAdRulesConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAdblockEngineRustGetDefaultAdRulesConstMeta =>
      const TaskConstMeta(
        debugName: "rust_get_default_ad_rules",
        argNames: [],
      );

  @override
  Future<String> crateApiSecurityRustGetDeviceFingerprint() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 29, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSecurityRustGetDeviceFingerprintConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSecurityRustGetDeviceFingerprintConstMeta =>
      const TaskConstMeta(
        debugName: "rust_get_device_fingerprint",
        argNames: [],
      );

  @override
  String crateApiRemoteRulesRustGetRulesStatus() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 30)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiRemoteRulesRustGetRulesStatusConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiRemoteRulesRustGetRulesStatusConstMeta =>
      const TaskConstMeta(
        debugName: "rust_get_rules_status",
        argNames: [],
      );

  @override
  Future<SupabaseSecrets> crateApiSecurityRustGetSupabaseConfig() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 31, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_supabase_secrets,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSecurityRustGetSupabaseConfigConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSecurityRustGetSupabaseConfigConstMeta =>
      const TaskConstMeta(
        debugName: "rust_get_supabase_config",
        argNames: [],
      );

  @override
  void crateApiAdblockEngineRustInitAdblocker({required List<String> rules}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_String(rules, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 32)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiAdblockEngineRustInitAdblockerConstMeta,
      argValues: [rules],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAdblockEngineRustInitAdblockerConstMeta =>
      const TaskConstMeta(
        debugName: "rust_init_adblocker",
        argNames: ["rules"],
      );

  @override
  Future<int> crateApiRemoteRulesRustInstallBundledRules(
      {required String json}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(json, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 33, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_32,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiRemoteRulesRustInstallBundledRulesConstMeta,
      argValues: [json],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiRemoteRulesRustInstallBundledRulesConstMeta =>
      const TaskConstMeta(
        debugName: "rust_install_bundled_rules",
        argNames: ["json"],
      );

  @override
  bool crateApiAdblockEngineRustShouldBlockUrl({required String url}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(url, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 34)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiAdblockEngineRustShouldBlockUrlConstMeta,
      argValues: [url],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAdblockEngineRustShouldBlockUrlConstMeta =>
      const TaskConstMeta(
        debugName: "rust_should_block_url",
        argNames: ["url"],
      );

  @override
  Future<String> crateApiSecurityRustSignMessage(
      {required String message, required String secret}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(message, serializer);
        sse_encode_String(secret, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 35, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSecurityRustSignMessageConstMeta,
      argValues: [message, secret],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSecurityRustSignMessageConstMeta =>
      const TaskConstMeta(
        debugName: "rust_sign_message",
        argNames: ["message", "secret"],
      );

  @override
  Future<void> crateApiRemoteRulesRustSyncRemoteRules({required String url}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(url, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 36, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiRemoteRulesRustSyncRemoteRulesConstMeta,
      argValues: [url],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiRemoteRulesRustSyncRemoteRulesConstMeta =>
      const TaskConstMeta(
        debugName: "rust_sync_remote_rules",
        argNames: ["url"],
      );

  @override
  Future<String> crateApiDownloaderSafeFilename(
      {required String title, required String format}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(title, serializer);
        sse_encode_String(format, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 37, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDownloaderSafeFilenameConstMeta,
      argValues: [title, format],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDownloaderSafeFilenameConstMeta =>
      const TaskConstMeta(
        debugName: "safe_filename",
        argNames: ["title", "format"],
      );

  @override
  void crateApiYtdlpWrapperSetCookiesPath({required String path}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 38)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiYtdlpWrapperSetCookiesPathConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiYtdlpWrapperSetCookiesPathConstMeta =>
      const TaskConstMeta(
        debugName: "set_cookies_path",
        argNames: ["path"],
      );

  @override
  void crateApiYtdlpWrapperSetProxyUrl({required String url}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(url, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 39)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiYtdlpWrapperSetProxyUrlConstMeta,
      argValues: [url],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiYtdlpWrapperSetProxyUrlConstMeta =>
      const TaskConstMeta(
        debugName: "set_proxy_url",
        argNames: ["url"],
      );

  @override
  void crateApiYtdlpWrapperSetYtdlpBinaryPath({required String path}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 40)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiYtdlpWrapperSetYtdlpBinaryPathConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiYtdlpWrapperSetYtdlpBinaryPathConstMeta =>
      const TaskConstMeta(
        debugName: "set_ytdlp_binary_path",
        argNames: ["path"],
      );

  @override
  Future<bool> crateApiStreamPolicyShouldPairSeparateAudio(
      {required bool isVideoOnly, required bool separateAudioTracksAvailable}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_bool(isVideoOnly, serializer);
        sse_encode_bool(separateAudioTracksAvailable, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 41, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiStreamPolicyShouldPairSeparateAudioConstMeta,
      argValues: [isVideoOnly, separateAudioTracksAvailable],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiStreamPolicyShouldPairSeparateAudioConstMeta =>
      const TaskConstMeta(
        debugName: "should_pair_separate_audio",
        argNames: ["isVideoOnly", "separateAudioTracksAvailable"],
      );

  @override
  Future<void> crateApiSecurityVaultDecryptFile(
      {required String vaultPath,
      required String outputPath,
      required String password}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(vaultPath, serializer);
        sse_encode_String(outputPath, serializer);
        sse_encode_String(password, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 42, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSecurityVaultDecryptFileConstMeta,
      argValues: [vaultPath, outputPath, password],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSecurityVaultDecryptFileConstMeta =>
      const TaskConstMeta(
        debugName: "vault_decrypt_file",
        argNames: ["vaultPath", "outputPath", "password"],
      );

  @override
  Future<void> crateApiSecurityVaultEncryptFile(
      {required String sourcePath,
      required String targetPath,
      required String password}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(sourcePath, serializer);
        sse_encode_String(targetPath, serializer);
        sse_encode_String(password, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 43, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSecurityVaultEncryptFileConstMeta,
      argValues: [sourcePath, targetPath, password],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSecurityVaultEncryptFileConstMeta =>
      const TaskConstMeta(
        debugName: "vault_encrypt_file",
        argNames: ["sourcePath", "targetPath", "password"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(dco_decode_list_record_string_string(raw)
        .map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  CommandNoWindow dco_decode_TraitDef_CommandNoWindow(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DownloadProgressSnapshot dco_decode_box_autoadd_download_progress_snapshot(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_download_progress_snapshot(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PlaylistResult dco_decode_box_autoadd_playlist_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_playlist_result(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  VideoInfoResult dco_decode_box_autoadd_video_info_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_video_info_result(raw);
  }

  @protected
  DownloadProgressSnapshot dco_decode_download_progress_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return DownloadProgressSnapshot(
      downloadedBytes: dco_decode_u_64(arr[0]),
      totalBytes: dco_decode_u_64(arr[1]),
      speedBytesSec: dco_decode_u_64(arr[2]),
      etaSeconds: dco_decode_u_64(arr[3]),
      percent: dco_decode_f_64(arr[4]),
      phase: dco_decode_String(arr[5]),
    );
  }

  @protected
  DownloadResult dco_decode_download_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DownloadResult(
      filePath: dco_decode_String(arr[0]),
      fileSizeBytes: dco_decode_u_64(arr[1]),
    );
  }

  @protected
  ExtractionResult dco_decode_extraction_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return ExtractionResult_Video(
          dco_decode_box_autoadd_video_info_result(raw[1]),
        );
      case 1:
        return ExtractionResult_Playlist(
          dco_decode_box_autoadd_playlist_result(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<PlatformRule> dco_decode_list_platform_rule(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_platform_rule).toList();
  }

  @protected
  List<PlaylistItem> dco_decode_list_playlist_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_playlist_item).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_string).toList();
  }

  @protected
  List<RuleStep> dco_decode_list_rule_step(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_rule_step).toList();
  }

  @protected
  List<StreamResult> dco_decode_list_stream_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_stream_result).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  DownloadProgressSnapshot?
      dco_decode_opt_box_autoadd_download_progress_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_download_progress_snapshot(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_32(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  PlatformRule dco_decode_platform_rule(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return PlatformRule(
      platform: dco_decode_String(arr[0]),
      version: dco_decode_u_32(arr[1]),
      patterns: dco_decode_Map_String_String_None(arr[2]),
      urlPatterns: dco_decode_list_String(arr[3]),
      userAgent: dco_decode_opt_String(arr[4]),
      priority: dco_decode_i_32(arr[5]),
      steps: dco_decode_list_rule_step(arr[6]),
    );
  }

  @protected
  PlaylistItem dco_decode_playlist_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return PlaylistItem(
      url: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      thumbnailUrl: dco_decode_opt_String(arr[2]),
      durationSeconds: dco_decode_opt_box_autoadd_u_32(arr[3]),
    );
  }

  @protected
  PlaylistResult dco_decode_playlist_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return PlaylistResult(
      title: dco_decode_String(arr[0]),
      author: dco_decode_opt_String(arr[1]),
      items: dco_decode_list_playlist_item(arr[2]),
    );
  }

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_String(arr[0]),
      dco_decode_String(arr[1]),
    );
  }

  @protected
  RuleStep dco_decode_rule_step(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return RuleStep_Fetch(
          url: dco_decode_String(raw[1]),
          asVar: dco_decode_String(raw[2]),
        );
      case 1:
        return RuleStep_RegexExtract(
          input: dco_decode_String(raw[1]),
          pattern: dco_decode_String(raw[2]),
          asVar: dco_decode_String(raw[3]),
        );
      case 2:
        return RuleStep_RegexFindAll(
          input: dco_decode_String(raw[1]),
          pattern: dco_decode_String(raw[2]),
          asVar: dco_decode_String(raw[3]),
        );
      case 3:
        return RuleStep_BuildStream(
          url: dco_decode_String(raw[1]),
          quality: dco_decode_String(raw[2]),
          container: dco_decode_String(raw[3]),
          isAudioOnly: dco_decode_bool(raw[4]),
        );
      case 4:
        return RuleStep_SetTitle(
          value: dco_decode_String(raw[1]),
        );
      case 5:
        return RuleStep_SetThumbnail(
          value: dco_decode_String(raw[1]),
        );
      case 6:
        return RuleStep_SetAuthor(
          value: dco_decode_String(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  RulesRegistry dco_decode_rules_registry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RulesRegistry(
      rules: dco_decode_list_platform_rule(arr[0]),
      lastUpdated: dco_decode_u_64(arr[1]),
    );
  }

  @protected
  StreamResult dco_decode_stream_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 15)
      throw Exception('unexpected arr length: expect 15 but see ${arr.length}');
    return StreamResult(
      url: dco_decode_String(arr[0]),
      quality: dco_decode_String(arr[1]),
      format: dco_decode_String(arr[2]),
      container: dco_decode_opt_String(arr[3]),
      width: dco_decode_opt_box_autoadd_u_32(arr[4]),
      height: dco_decode_opt_box_autoadd_u_32(arr[5]),
      fps: dco_decode_opt_box_autoadd_f_32(arr[6]),
      videoCodec: dco_decode_opt_String(arr[7]),
      audioCodec: dco_decode_opt_String(arr[8]),
      bitrateKbps: dco_decode_opt_box_autoadd_u_32(arr[9]),
      fileSizeBytes: dco_decode_opt_box_autoadd_u_64(arr[10]),
      hasVideo: dco_decode_bool(arr[11]),
      hasAudio: dco_decode_bool(arr[12]),
      isAudioOnly: dco_decode_bool(arr[13]),
      isHdr: dco_decode_bool(arr[14]),
    );
  }

  @protected
  SupabaseSecrets dco_decode_supabase_secrets(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SupabaseSecrets(
      url: dco_decode_String(arr[0]),
      anonKey: dco_decode_String(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  VideoInfoResult dco_decode_video_info_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return VideoInfoResult(
      title: dco_decode_String(arr[0]),
      thumbnailUrl: dco_decode_opt_String(arr[1]),
      platform: dco_decode_String(arr[2]),
      durationSeconds: dco_decode_opt_box_autoadd_u_32(arr[3]),
      author: dco_decode_opt_String(arr[4]),
      streams: dco_decode_list_stream_result(arr[5]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_record_string_string(deserializer);
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DownloadProgressSnapshot sse_decode_box_autoadd_download_progress_snapshot(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_download_progress_snapshot(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_32(deserializer));
  }

  @protected
  PlaylistResult sse_decode_box_autoadd_playlist_result(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_playlist_result(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  VideoInfoResult sse_decode_box_autoadd_video_info_result(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_video_info_result(deserializer));
  }

  @protected
  DownloadProgressSnapshot sse_decode_download_progress_snapshot(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_downloadedBytes = sse_decode_u_64(deserializer);
    var var_totalBytes = sse_decode_u_64(deserializer);
    var var_speedBytesSec = sse_decode_u_64(deserializer);
    var var_etaSeconds = sse_decode_u_64(deserializer);
    var var_percent = sse_decode_f_64(deserializer);
    var var_phase = sse_decode_String(deserializer);
    return DownloadProgressSnapshot(
        downloadedBytes: var_downloadedBytes,
        totalBytes: var_totalBytes,
        speedBytesSec: var_speedBytesSec,
        etaSeconds: var_etaSeconds,
        percent: var_percent,
        phase: var_phase);
  }

  @protected
  DownloadResult sse_decode_download_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_filePath = sse_decode_String(deserializer);
    var var_fileSizeBytes = sse_decode_u_64(deserializer);
    return DownloadResult(
        filePath: var_filePath, fileSizeBytes: var_fileSizeBytes);
  }

  @protected
  ExtractionResult sse_decode_extraction_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_box_autoadd_video_info_result(deserializer);
        return ExtractionResult_Video(var_field0);
      case 1:
        var var_field0 = sse_decode_box_autoadd_playlist_result(deserializer);
        return ExtractionResult_Playlist(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<PlatformRule> sse_decode_list_platform_rule(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PlatformRule>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_platform_rule(deserializer));
    }
    return ans_;
  }

  @protected
  List<PlaylistItem> sse_decode_list_playlist_item(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PlaylistItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_playlist_item(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_string(deserializer));
    }
    return ans_;
  }

  @protected
  List<RuleStep> sse_decode_list_rule_step(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RuleStep>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rule_step(deserializer));
    }
    return ans_;
  }

  @protected
  List<StreamResult> sse_decode_list_stream_result(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <StreamResult>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_stream_result(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  DownloadProgressSnapshot?
      sse_decode_opt_box_autoadd_download_progress_snapshot(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_download_progress_snapshot(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformRule sse_decode_platform_rule(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_platform = sse_decode_String(deserializer);
    var var_version = sse_decode_u_32(deserializer);
    var var_patterns = sse_decode_Map_String_String_None(deserializer);
    var var_urlPatterns = sse_decode_list_String(deserializer);
    var var_userAgent = sse_decode_opt_String(deserializer);
    var var_priority = sse_decode_i_32(deserializer);
    var var_steps = sse_decode_list_rule_step(deserializer);
    return PlatformRule(
        platform: var_platform,
        version: var_version,
        patterns: var_patterns,
        urlPatterns: var_urlPatterns,
        userAgent: var_userAgent,
        priority: var_priority,
        steps: var_steps);
  }

  @protected
  PlaylistItem sse_decode_playlist_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_url = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_thumbnailUrl = sse_decode_opt_String(deserializer);
    var var_durationSeconds = sse_decode_opt_box_autoadd_u_32(deserializer);
    return PlaylistItem(
        url: var_url,
        title: var_title,
        thumbnailUrl: var_thumbnailUrl,
        durationSeconds: var_durationSeconds);
  }

  @protected
  PlaylistResult sse_decode_playlist_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_author = sse_decode_opt_String(deserializer);
    var var_items = sse_decode_list_playlist_item(deserializer);
    return PlaylistResult(
        title: var_title, author: var_author, items: var_items);
  }

  @protected
  (String, String) sse_decode_record_string_string(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  RuleStep sse_decode_rule_step(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_url = sse_decode_String(deserializer);
        var var_asVar = sse_decode_String(deserializer);
        return RuleStep_Fetch(url: var_url, asVar: var_asVar);
      case 1:
        var var_input = sse_decode_String(deserializer);
        var var_pattern = sse_decode_String(deserializer);
        var var_asVar = sse_decode_String(deserializer);
        return RuleStep_RegexExtract(
            input: var_input, pattern: var_pattern, asVar: var_asVar);
      case 2:
        var var_input = sse_decode_String(deserializer);
        var var_pattern = sse_decode_String(deserializer);
        var var_asVar = sse_decode_String(deserializer);
        return RuleStep_RegexFindAll(
            input: var_input, pattern: var_pattern, asVar: var_asVar);
      case 3:
        var var_url = sse_decode_String(deserializer);
        var var_quality = sse_decode_String(deserializer);
        var var_container = sse_decode_String(deserializer);
        var var_isAudioOnly = sse_decode_bool(deserializer);
        return RuleStep_BuildStream(
            url: var_url,
            quality: var_quality,
            container: var_container,
            isAudioOnly: var_isAudioOnly);
      case 4:
        var var_value = sse_decode_String(deserializer);
        return RuleStep_SetTitle(value: var_value);
      case 5:
        var var_value = sse_decode_String(deserializer);
        return RuleStep_SetThumbnail(value: var_value);
      case 6:
        var var_value = sse_decode_String(deserializer);
        return RuleStep_SetAuthor(value: var_value);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  RulesRegistry sse_decode_rules_registry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_rules = sse_decode_list_platform_rule(deserializer);
    var var_lastUpdated = sse_decode_u_64(deserializer);
    return RulesRegistry(rules: var_rules, lastUpdated: var_lastUpdated);
  }

  @protected
  StreamResult sse_decode_stream_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_url = sse_decode_String(deserializer);
    var var_quality = sse_decode_String(deserializer);
    var var_format = sse_decode_String(deserializer);
    var var_container = sse_decode_opt_String(deserializer);
    var var_width = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_height = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_fps = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_videoCodec = sse_decode_opt_String(deserializer);
    var var_audioCodec = sse_decode_opt_String(deserializer);
    var var_bitrateKbps = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_fileSizeBytes = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_hasVideo = sse_decode_bool(deserializer);
    var var_hasAudio = sse_decode_bool(deserializer);
    var var_isAudioOnly = sse_decode_bool(deserializer);
    var var_isHdr = sse_decode_bool(deserializer);
    return StreamResult(
        url: var_url,
        quality: var_quality,
        format: var_format,
        container: var_container,
        width: var_width,
        height: var_height,
        fps: var_fps,
        videoCodec: var_videoCodec,
        audioCodec: var_audioCodec,
        bitrateKbps: var_bitrateKbps,
        fileSizeBytes: var_fileSizeBytes,
        hasVideo: var_hasVideo,
        hasAudio: var_hasAudio,
        isAudioOnly: var_isAudioOnly,
        isHdr: var_isHdr);
  }

  @protected
  SupabaseSecrets sse_decode_supabase_secrets(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_url = sse_decode_String(deserializer);
    var var_anonKey = sse_decode_String(deserializer);
    return SupabaseSecrets(url: var_url, anonKey: var_anonKey);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  VideoInfoResult sse_decode_video_info_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_thumbnailUrl = sse_decode_opt_String(deserializer);
    var var_platform = sse_decode_String(deserializer);
    var var_durationSeconds = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_author = sse_decode_opt_String(deserializer);
    var var_streams = sse_decode_list_stream_result(deserializer);
    return VideoInfoResult(
        title: var_title,
        thumbnailUrl: var_thumbnailUrl,
        platform: var_platform,
        durationSeconds: var_durationSeconds,
        author: var_author,
        streams: var_streams);
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_Map_String_String_None(
      Map<String, String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_string(
        self.entries.map((e) => (e.key, e.value)).toList(), serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_download_progress_snapshot(
      DownloadProgressSnapshot self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_download_progress_snapshot(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_playlist_result(
      PlaylistResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_playlist_result(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_video_info_result(
      VideoInfoResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_video_info_result(self, serializer);
  }

  @protected
  void sse_encode_download_progress_snapshot(
      DownloadProgressSnapshot self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.downloadedBytes, serializer);
    sse_encode_u_64(self.totalBytes, serializer);
    sse_encode_u_64(self.speedBytesSec, serializer);
    sse_encode_u_64(self.etaSeconds, serializer);
    sse_encode_f_64(self.percent, serializer);
    sse_encode_String(self.phase, serializer);
  }

  @protected
  void sse_encode_download_result(
      DownloadResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.filePath, serializer);
    sse_encode_u_64(self.fileSizeBytes, serializer);
  }

  @protected
  void sse_encode_extraction_result(
      ExtractionResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case ExtractionResult_Video(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_box_autoadd_video_info_result(field0, serializer);
      case ExtractionResult_Playlist(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_box_autoadd_playlist_result(field0, serializer);
    }
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_platform_rule(
      List<PlatformRule> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_platform_rule(item, serializer);
    }
  }

  @protected
  void sse_encode_list_playlist_item(
      List<PlaylistItem> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_playlist_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_string(
      List<(String, String)> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_string(item, serializer);
    }
  }

  @protected
  void sse_encode_list_rule_step(
      List<RuleStep> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rule_step(item, serializer);
    }
  }

  @protected
  void sse_encode_list_stream_result(
      List<StreamResult> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_stream_result(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_download_progress_snapshot(
      DownloadProgressSnapshot? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_download_progress_snapshot(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_platform_rule(PlatformRule self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.platform, serializer);
    sse_encode_u_32(self.version, serializer);
    sse_encode_Map_String_String_None(self.patterns, serializer);
    sse_encode_list_String(self.urlPatterns, serializer);
    sse_encode_opt_String(self.userAgent, serializer);
    sse_encode_i_32(self.priority, serializer);
    sse_encode_list_rule_step(self.steps, serializer);
  }

  @protected
  void sse_encode_playlist_item(PlaylistItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.url, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_opt_String(self.thumbnailUrl, serializer);
    sse_encode_opt_box_autoadd_u_32(self.durationSeconds, serializer);
  }

  @protected
  void sse_encode_playlist_result(
      PlaylistResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_opt_String(self.author, serializer);
    sse_encode_list_playlist_item(self.items, serializer);
  }

  @protected
  void sse_encode_record_string_string(
      (String, String) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_rule_step(RuleStep self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case RuleStep_Fetch(url: final url, asVar: final asVar):
        sse_encode_i_32(0, serializer);
        sse_encode_String(url, serializer);
        sse_encode_String(asVar, serializer);
      case RuleStep_RegexExtract(
          input: final input,
          pattern: final pattern,
          asVar: final asVar
        ):
        sse_encode_i_32(1, serializer);
        sse_encode_String(input, serializer);
        sse_encode_String(pattern, serializer);
        sse_encode_String(asVar, serializer);
      case RuleStep_RegexFindAll(
          input: final input,
          pattern: final pattern,
          asVar: final asVar
        ):
        sse_encode_i_32(2, serializer);
        sse_encode_String(input, serializer);
        sse_encode_String(pattern, serializer);
        sse_encode_String(asVar, serializer);
      case RuleStep_BuildStream(
          url: final url,
          quality: final quality,
          container: final container,
          isAudioOnly: final isAudioOnly
        ):
        sse_encode_i_32(3, serializer);
        sse_encode_String(url, serializer);
        sse_encode_String(quality, serializer);
        sse_encode_String(container, serializer);
        sse_encode_bool(isAudioOnly, serializer);
      case RuleStep_SetTitle(value: final value):
        sse_encode_i_32(4, serializer);
        sse_encode_String(value, serializer);
      case RuleStep_SetThumbnail(value: final value):
        sse_encode_i_32(5, serializer);
        sse_encode_String(value, serializer);
      case RuleStep_SetAuthor(value: final value):
        sse_encode_i_32(6, serializer);
        sse_encode_String(value, serializer);
    }
  }

  @protected
  void sse_encode_rules_registry(RulesRegistry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_platform_rule(self.rules, serializer);
    sse_encode_u_64(self.lastUpdated, serializer);
  }

  @protected
  void sse_encode_stream_result(StreamResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.url, serializer);
    sse_encode_String(self.quality, serializer);
    sse_encode_String(self.format, serializer);
    sse_encode_opt_String(self.container, serializer);
    sse_encode_opt_box_autoadd_u_32(self.width, serializer);
    sse_encode_opt_box_autoadd_u_32(self.height, serializer);
    sse_encode_opt_box_autoadd_f_32(self.fps, serializer);
    sse_encode_opt_String(self.videoCodec, serializer);
    sse_encode_opt_String(self.audioCodec, serializer);
    sse_encode_opt_box_autoadd_u_32(self.bitrateKbps, serializer);
    sse_encode_opt_box_autoadd_u_64(self.fileSizeBytes, serializer);
    sse_encode_bool(self.hasVideo, serializer);
    sse_encode_bool(self.hasAudio, serializer);
    sse_encode_bool(self.isAudioOnly, serializer);
    sse_encode_bool(self.isHdr, serializer);
  }

  @protected
  void sse_encode_supabase_secrets(
      SupabaseSecrets self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.url, serializer);
    sse_encode_String(self.anonKey, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_video_info_result(
      VideoInfoResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_opt_String(self.thumbnailUrl, serializer);
    sse_encode_String(self.platform, serializer);
    sse_encode_opt_box_autoadd_u_32(self.durationSeconds, serializer);
    sse_encode_opt_String(self.author, serializer);
    sse_encode_list_stream_result(self.streams, serializer);
  }
}
