import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

class AppLocalization {
  static const List<Locale> supportedLocales = [Locale('ar'), Locale('en')];

  static const List<LocalizationsDelegate> localizationsDelegates = [
    GlobalMaterialLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate,
    GlobalCupertinoLocalizations.delegate,
  ];

  static const Map<String, String> ar = {
    // عام
    'app_name': 'دارك',
    'bootstrap_engine_failed_debug': 'تعذّر تشغيل المحرك الأصلي.\n\n{detail}',
    'bootstrap_engine_failed_release': 'تعذّر تشغيل المحرك الأصلي. راجع السجلات أو أعد تثبيت التطبيق.',
    'profile_guest_name': 'ضيف',
    'profile_seed_display_name': 'مستخدم دارك',
    'profile_no_email': 'لم يتم تسجيل الدخول',
    'subscription_tier_free': 'مجاني',
    'profile_theme_color_title': 'لون التطبيق',
    'profile_theme_color_subtitle': 'اختر لونك المفضل للواجهة',
    'profile_user_id_unknown': 'غير معروف',
    'windows_url_protocol_desc': 'URL:{name} — بروتوكول',
    'welcome': 'مرحباً بك',
    'welcome_back': 'مرحباً بك مجدداً',
    'loading': 'جاري التحميل...',
    'error': 'خطأ',
    'success': 'تم بنجاح',
    'failed': 'فشلت العملية',
    'cancel': 'إلغاء',
    'save': 'حفظ',
    'delete': 'حذف',
    'edit': 'تعديل',
    'retry': 'إعادة المحاولة',
    'close': 'إغلاق',
    'confirm': 'تأكيد',
    'privacy_policy': 'سياسة الخصوصية',
    'terms_of_service': 'شروط الاستخدام',
    'privacy_policy_content': 'سياسة الخصوصية لـ دارك:\n\n1. الأمان: بياناتك مشفرة ومحمية بأحدث التقنيات.\n2. الاستخدام: نستخدم البيانات فقط لتحسين تجربة المستخدم وتقديم خدماتنا.\n3. الخصوصية: ملفاتك وخصوصيتك هي أولويتنا القصوى.',
    'terms_of_service_content': 'شروط استخدام دارك:\n\n1. الاشتراك: ميزات PRO تتطلب اشتراكاً نشطاً.\n2. سياسة الاسترداد: بما أن الخدمة رقمية، لا يمكن استرداد الأموال بعد تفعيل ميزات PRO أو بدء أول عملية تحميل.\n3. الاستخدام العادل: يمنع استخدام التطبيق لتحميل محتوى ينتهك حقوق الملكية الفكرية.',
    'or': 'أو',
    'yes': 'نعم',
    'no': 'لا',

    // مصادقة
    'login': 'تسجيل الدخول',
    'signup': 'إنشاء حساب',
    'logout': 'تسجيل الخروج',
    'email': 'البريد الإلكتروني',
    'password': 'كلمة المرور',
    'create_account': 'إنشاء حساب جديد',
    'already_have_account': 'لديك حساب بالفعل؟',
    'no_account': 'ليس لديك حساب؟',
    'forgot_password': 'نسيت كلمة المرور؟',
    'reset_password': 'إعادة تعيين كلمة المرور',
    'confirm_logout': 'هل تريد تسجيل الخروج؟',

    // تنقل
    'home': 'الرئيسية',
    'downloads': 'التحميلات',
    'profile': 'الملف الشخصي',
    'browser': 'المتصفح',
    'settings': 'الإعدادات',
    'search': 'بحث',

    // الرئيسية
    'paste_url': 'الصق رابط الفيديو هنا',
    'browse_web': 'تصفح المواقع',
    'enter_url': 'أدخل رابط الفيديو',
    'analyze': 'تحليل',
    'analyzing': 'جاري التحليل...',
    'suggested_link_title': 'رابط مقترح من الحافظة',
    'supported_platforms': 'المنصات المدعومة',
    'quick_download': 'تحميل سريع',
    'bypass_blocks_label': 'تجاوز حجب المواقع',
    'bypass_blocks_hint': 'استخدم خوادم وسيطة للوصول للمواقع المحجوبة بدون VPN',
    'recent_downloads': 'التحميلات الأخيرة',
    'no_recent': 'لا توجد تحميلات حديثة',
    'see_all': 'عرض الكل',
    'tips': 'نصائح',
    'tip_1': 'الصق أي رابط فيديو من المنصات المدعومة',
    'tip_2': 'اختر الجودة المناسبة قبل التحميل',
    'tip_3': 'يمكنك تحميل الصوت فقط بدون فيديو',

    // تحميل
    'download': 'تحميل',
    'downloading': 'جاري التحميل',
    'download_complete': 'اكتمل التحميل',
    'download_failed': 'فشل التحميل',
    'add_to_queue': 'إضافة للقائمة',
    'download_options': 'خيارات التحميل',
    'quality': 'الجودة',
    'format': 'الصيغة',
    'audio_only': 'صوت فقط',
    'with_subtitles': 'مع الترجمة',
    'file_size': 'حجم الملف',
    'duration': 'المدة',
    'platform': 'المنصة',
    'no_downloads': 'لا توجد تحميلات حالياً',
    'clear_all': 'مسح الكل',
    'start_download': 'ابدأ التحميل',
    'estimated_size': 'الحجم التقديري',
    'video_info': 'معلومات الفيديو',
    'unsupported_platform': 'المنصة غير مدعومة',
    'invalid_url': 'الرابط غير صحيح',
    'download_captured': 'تحميل الفيديو المكتشف',
    'download_open_folder': 'فتح مجلد الملف',
    'download_saved_in': 'المسار',
    'download_file_missing_snack':
        'الملف غير موجود في هذا المسار. افتح المجلد من الزر بجانب التشغيل أو تحقق من مجلد التحميلات \\ DarkDownloader',
    'search_or_url': 'ابحث أو أدخل رابطاً',
    'videos_found': 'تم اكتشاف فيديوهات',
    'detected_videos': 'الفيديوهات المكتشفة',
    'items': 'عناصر',
    'browser_recent': 'الصفحات الأخيرة',
    'browser_copy_link': 'نسخ عنوان الرابط الحالي',
    'browser_open_external': 'فتح في المتصفح الافتراضي',
    'browser_clear_history': 'مسح السجل',
    'browser_empty_history': 'لا توجد صفحات في السجل بعد',
    'browser_new_tab': 'تبويب جديد',
    'browser_analyze_page': 'تحليل الصفحة للتحميل',
    'browser_queue_best': 'أفضل جودة → الطابور',
    'browser_choose_quality': 'اختيار الجودة',
    'browser_incognito_mode': 'وضع التصفح المتخفي',
    'adblock_title': 'مانع الإعلانات',
    'adblock_subtitle': 'حجب الإعلانات والنوافذ المنبثقة',
    'adblock_custom_rules': 'قواعد مخصصة',
    'adblock_add_rule': 'إضافة قاعدة',
    'adblock_rule_hint': 'مثال: ||ads.example.com^',
    'browser_queue_not_added':
        'تعذر الإضافة (صلاحيات، اشتراك، أو التحميل نشط لنفس الفيديو).',
    'browser_refresh': 'تحديث',
    'browser_desktop_site': 'نسخة سطح المكتب',
    'browser_mobile_site': 'نسخة الجوال',
    'browser_clear_detected': 'مسح المكتشف',
    'browser_link_copied': 'تم نسخ الرابط',
    'browser_no_url': 'لا يوجد رابط صالح في شريط العنوان',
    'browser_unsafe_url': 'رابط غير مسموح (يُقبل http أو https فقط).',
    'browser_detected_subtitle': 'روابط الوسائط تُلتقط تلقائياً على سطح المكتب',
    'browser_downloads_library': 'مكتبة التحميلات',
    'browser_tabs': 'التبويبات',
    'browser_more': 'المزيد',
    'browser_tools': 'أدوات المتصفح',
    'browser_stop': 'إيقاف',
    'browser_extract_failed': 'تعذّر استخراج فيديو من هذه الصفحة',
    'browser_back': 'رجوع',
    'browser_forward': 'أمام',
    'browser_find_in_page': 'بحث في الصفحة',
    'browser_find_hint': 'اكتب للبحث داخل الصفحة',
    'browser_find_next': 'التالي',
    'browser_find_close': 'إغلاق',
    'browser_duplicate_tab': 'نسخ التبويب',
    'browser_close_other_tabs': 'إغلاق بقية التبويبات',
    'browser_share_link': 'مشاركة الرابط',
    'browser_whitelisted': 'موقع موثوق (مانع الإعلانات معطل)',
    'browser_add_to_whitelist': 'إضافة للمواقع الموثوقة',
    'pause': 'إيقاف',
    'resume': 'استئناف',
    'browser_queue_all': 'إضافة الكل للطابور (أفضل جودة)',
    'browser_queue_all_progress': 'جاري إضافة العناصر المكتشفة…',
    'browser_queue_all_summary': 'من {total}: أضيف {added}، تخطي {skipped}، فشل {failed}',
    'browser_queue_all_step': '{current} / {total}',
    'browser_queue_all_cancel': 'إيقاف',
    'browser_queue_all_stopped': 'توقفت مبكراً: أضيف {added}، تخطي {skipped}، فشل {failed} من أصل {total}.',
    'bookmarks': 'الإشارات المرجعية',
    'browser_history_cloud_hint':
        'سجلك محلياً؛ عند تسجيل الدخول يُدمج مع السحابة. زر المزامنة يسحب ويرفع آخر القائمة.',
    'browser_history_pull_cloud': 'مزامنة مع السحابة',
    'browser_sync_ok': 'تمت المزامنة',
    'browser_sync_fail': 'تعذّرت المزامنة. تأكد من الجدول في Supabase أو الشبكة.',

    // الملف الشخصي
    'my_profile': 'ملفي الشخصي',
    'profile_display_name_fallback': 'مستخدم',
    'account_info': 'معلومات الحساب',
    'subscription_info': 'معلومات الاشتراك',
    'subscription': 'الاشتراك',
    'current_plan': 'خطتك الحالية',
    'upgrade': 'ترقية',
    'plan_free': 'مجاني',
    'plan_premium': 'مميز',
    'plan_pro': 'احترافي',
    'active': 'نشط',
    'inactive': 'غير نشط',
    'expires': 'ينتهي في',
    'total_downloads': 'مجموع التحميلات',
    'about': 'حول التطبيق',
    'language': 'اللغة',
    'floating_dl_title': 'زر التحميل العائم',
    'floating_dl_subtitle':
        'زر صغير فوق التطبيقات الأخرى. انسخ رابط الفيديو من المتصفح أو التواصل، ثم اضغط الزر لإرساله إلى التطبيق. لا يُسمح للنظام بإدراج زر داخل مشغّل الفيديو في تطبيقات الغير.',
    'theme': 'المظهر',
    'theme_follow_system': 'كمظهر الجهاز',
    'dark_mode': 'الوضع الليلي',
    'light_mode': 'الوضع النهاري',
    'arabic': 'العربية',
    'english': 'English',
    'profile_pick_accent': 'اختر لون الواجهة',
    'profile_upgrade_pro_title': 'رقِّ حسابك إلى PRO',
    'profile_upgrade_pro_subtitle': 'سرعة أعلى، تحميلات غير محدودة وميزات حصرية',

    // الاشتراكات
    'plans': 'خطط الاشتراك',
    'choose_plan': 'اختر خطتك',
    'per_month': 'شهرياً',
    'popular': 'الأكثر طلباً',
    'cancel_subscription': 'إلغاء الاشتراك',
    'confirm_cancel': 'هل أنت متأكد من إلغاء الاشتراك؟',
    'select_plan': 'اختر هذه الخطة',
    'subscription_screen_title': 'ترقية الحساب',
    'subscription_headline': 'اختر خطتك المناسبة',
    'subscription_tagline':
        'تطبيق موجّه عالمياً: اشترك بـ PRO عبر بوابة دفع آمنة (FIB) حيث يوفّر البنك خدمة الدفع رسمياً.',
    'subscription_tier_premium': 'PREMIUM',
    'subscription_tier_pro': 'PRO',
    'subscription_price_premium': r'9.99$',
    'subscription_price_pro': r'19.99$',
    'subscription_period_slash_month': '/ شهر',
    'subscription_local_payment': 'دفع عبر FIB (حيث يتوفر)',
    'subscription_pay_fib': 'الدفع عبر FIB',
    'subscription_fib_sandbox_note':
        'للمطورين: إعدادات الاختبار على fib-stage.fib.iq؛ أسرار FIB في Supabase Edge Functions.',
    'subscription_subscribe_now': 'اشترك الآن',
    'subscription_premium_f1': 'تحميلات غير محدودة',
    'subscription_premium_f2': 'جودة حتى 1080p (Full HD)',
    'subscription_premium_f3': 'بدون إعلانات نهائياً',
    'subscription_premium_f4': 'دعم فني عبر البريد',
    'subscription_pro_f1': 'كل ميزات Premium',
    'subscription_pro_f2': 'جودة 4K Ultra HD',
    'subscription_pro_f3': 'تحميل 5 ملفات في وقت واحد',
    'subscription_pro_f4': 'دعم فني فوري (Live Chat)',
    'subscription_pro_f5': 'أولوية في تحديثات الميزات',
    'trial_expired': 'انتهت الفترة التجريبية. اشترك للمتابعة.',
    'trial_remaining': 'متبقي من التجربة: {h} ساعة',
    'subscribe_to_continue': 'يلزم الاشتراك للمتابعة',
    'subscription_period_monthly': 'شهري',
    'subscription_period_yearly': 'سنوي',
    'subscription_price_monthly': r'$1.5',
    'subscription_price_yearly': r'$15',

    // رسائل
    'network_error': 'خطأ في الاتصال، تحقق من الإنترنت',
    'added_to_queue': 'تمت الإضافة لقائمة التحميل',
    'playlist_preparing': 'جارٍ تجهيز قائمة التشغيل...',
    'playlist_added_batch': 'تمت إضافة {n} من العناصر إلى قائمة التحميل',
    'playlist_nothing_enqueued': 'لم تُضف أي عنصر إلى قائمة التحميل. تحقق من الروابط أو حاول مجدداً.',
    'playlist_download_selected': 'تحميل المختار ({n})',
    'downloads_empty_local': 'لا توجد تحميلات في القائمة',
    'cloud_history_empty': 'لا يوجد سجل سحابي بعد',
    'cloud_history_load_error': 'تعذّر تحميل السجل: {detail}',
    'history_kind_torrent': 'نوع الملف: تورنت',
    'history_copied_magnet': 'تم نسخ الرابط المغناطيسي',
    'history_copied_video_url': 'تم نسخ رابط الفيديو',
    'dm_fallback_failed': 'فشل التحميل',
    'dm_eta_remaining': 'المتبقي: {eta}',
    'dm_move_queue_up': 'أولوية أعلى في الطابور',
    'dm_move_queue_down': 'أولوية أقل في الطابور',
    'dm_schedule_section_title': 'جدولة التحميل (مثلاً وقت النوم)',
    'dm_schedule_subtitle_now': 'التحميل فوراً',
    'dm_schedule_subtitle_at': 'سيبدأ في: {time}',
    'dm_schedule_toggle': 'تحميل في وقت محدد',
    'dm_schedule_picker_help': 'اختر وقت بدء التحميل',
    'removed_from_queue': 'تمت الإزالة من القائمة',
    'copied': 'تم النسخ',

    'confirm_clear_downloads':
        'مسح كل عناصر قائمة التحميل من هذا الجهاز؟ لا يمكن التراجع.',
    'generic_error_detail': 'حدث خطأ: {detail}',

    'format_percent': '{p}%',
    /// يُلحق بحجم البيانات للسرعة، مثل `12 MB/ث`.
    'data_rate_suffix': '/ث',

    'eta_under_minute': '{n} ث',
    'eta_under_hour': '{m} د {s} ث',
    'eta_under_day': '{h} س {m} د',
    'eta_days': '{d} ي {h} س',

    // منتقي الجودة — أنواع التدفقات
    'kind_muxed': 'فيديو (صورة وصوت)',
    'kind_video_only': 'فيديو فقط',
    'kind_audio_only': 'صوت فقط',

    // منتقي الجودة — مرشّحات
    'filter_resolution': 'الدقة',
    'filter_format': 'الصيغة',
    'filter_kind': 'النوع',
    'filter_all': 'الكل',
    'filter_video_with_audio': 'فيديو (صورة وصوت)',

    'merge_banner_title': 'سيتم دمج الصوت مع الفيديو',
    'merge_banner_body':
        'هذا المسار يحتاج صوتاً منفصلاً — سيدمج التطبيق الملفين تلقائياً.',
    'merge_missing_audio': 'اختر مساراً صوتياً للدمج مع الفيديو',

    // بيانات وصفية للتدفق
    'stream_codec_audio': 'صوت',
    'stream_codec_video': 'فيديو',
    'stream_codec_unknown': '—',
    'stream_bitrate_kbps': '{n} كيلوبت/ث',

    'platform_youtube': 'يوتيوب',
    'platform_tiktok': 'تيك توك',
    'platform_instagram': 'إنستغرام',
    'platform_twitter': 'تويتر / X',
    'platform_facebook': 'فيسبوك',
    'platform_vimeo': 'فيميو',
    'platform_dailymotion': 'ديليموشن',
    'platform_soundcloud': 'ساوند كلاود',
    'platform_reddit': 'ريديت',
    'platform_twitch': 'تويتش',
    'platform_pinterest': 'بنترست',
    'platform_rumble': 'رامبل',

    'about_app_subtitle': '{name} — الإصدار {version}',
    'about_legalese': '© {year} {name}',
    'company_info': 'معلومات الشركة',
    'contact_us': 'تواصل معنا',
    'contact_phone': 'الهاتف',
    'contact_whatsapp': 'واتساب',
    'contact_email': 'البريد',
    'contact_website': 'الموقع',
    'contact_facebook': 'فيسبوك',
    'contact_instagram': 'إنستغرام',

    'codec': 'المرمّز',
    'bitrate': 'معدل البت',
    'fps': 'إطار/ث',
    'resolution': 'الدقة',
    'container': 'الحاوية',
    'selected_quality': 'الجودة المختارة',
    'best_quality': 'أفضل جودة',
    'no_streams_for_filter': 'لا توجد روابط مطابقة للمرشّحات الحالية',

    // ويب
    'platform_banner_web_title': 'أنت تستخدم نسخة الويب',
    'platform_banner_desktop_encoder_title': 'إعداد مكوّن الدمج (مرة واحدة)',
    'platform_banner_desktop_encoder_body':
        'لا يمكن دمج الفيديو والصوت: المحرك الأسطوري غير جاهز مؤقتاً. يرجى تجربة «إعادة المحاولة» لاحقاً.',
    'platform_banner_desktop_encoder_retry': 'إعادة المحاولة',
    'platform_banner_web_body':
        'قد تكون ميزات مثل BitTorrent والتحميل الاحتياطي محدودة. لأفضل تجربة استخدم تطبيق سطح المكتب أو Android.',

    // خادم (RequireAuth)
    'backend_unavailable_title': 'الخدمة غير متاحة',
    'backend_unavailable_body':
        'لا يمكن الاتصال بالخادم حالياً. مزامنة الحساب والاشتراك غير متاحة، ويمكنك الاستمرار في التحميل المباشر.',
    'backend_unavailable_login_title': 'لم يُضبط Supabase بعد',
    'backend_unavailable_login_lead':
        'لن يعمل تسجيل الدخول حتى يقرأ التطبيق عنوان المشروع ومفتاح anon. اختر طريقة واحدة:',
    'backend_unavailable_login_opt_dart_define':
        'عند التشغيل/البناء أضِف:\n--dart-define=SUPABASE_URL=https://….supabase.co\n--dart-define=SUPABASE_ANON_KEY=…',
    'backend_unavailable_login_opt_file':
        'أو أنشئ الملف بالمسار أدناه (UTF-8) باسم supabase_local.json ثم أعد تشغيل التطبيق.',
    'backend_unavailable_login_path_label': 'مسار الملف',
    'backend_unavailable_login_open_folder': 'فتح المجلد',
    'backend_unavailable_login_copy_path': 'نسخ المسار',
    'backend_unavailable_login_view_example': 'عرض مثال JSON',
    'backend_unavailable_login_copied': 'تم نسخ المسار',
    'backend_unavailable_login_restart':
        'بعد حفظ الملف أو تغيير الإعدادات أغلق التطبيق بالكامل وافتحه من جديد.',
    'backend_unavailable_login_release_local_disabled':
        'إصدار الإنتاج لا يقرأ ملف supabase_local.json إلا إذا بُني التطبيق بـ ALLOW_SUPABASE_LOCAL_FILE=true — استخدم dart-define أو الإعداد المدمج للمتجر.',
    'backend_unavailable_login_hint':
        'لم يُضبط Supabase. راجع بطاقة الإعداد أعلاه أو أضِف dart-define عند البناء.',

    // تورنت — عام
    'magnet_added': 'تمت إضافة المغناطيس',
    'torrent_label': 'تورنت',
    'torrent_title': 'التورنت',
    'torrent_engine_init_failed': 'فشل تهيئة محرك التورنت:',
    'torrent_tab_active': 'نشط ({n})',
    'torrent_tab_seeding': 'يبذر ({n})',
    'torrent_tab_completed': 'مكتمل ({n})',
    'torrent_tab_all': 'الكل',
    'torrent_search_tooltip': 'بحث',
    'torrent_add_fab': 'إضافة تورنت',
    'torrent_empty_filter': 'لا يوجد تورنت في هذا التصنيف',
    'torrent_error': 'خطأ: {e}',
    'torrent_menu_pause': 'إيقاف مؤقت',
    'torrent_menu_resume': 'استئناف',
    'torrent_menu_remove': 'حذف من القائمة',
    'torrent_menu_remove_with_files': 'حذف مع الملفات',
    'torrent_stats_line': 'نشط {a} · بذر {s}',
    'home_torrent_unsupported': 'التورنت غير متاح على هذا الجهاز',
    'torrent_unsupported_title': 'BitTorrent غير مدعوم على هذه المنصة.',
    'torrent_unsupported_subtitle':
        'استخدم Windows أو macOS أو Linux أو Android.',
    'torrent_err_add_magnet': 'فشل إضافة Magnet',
    'torrent_err_add_torrent_file': 'فشل إضافة ملف torrent',
    'torrent_err_pause': 'فشل الإيقاف المؤقت',
    'torrent_err_resume': 'فشل الاستئناف',
    'torrent_err_remove': 'فشل الحذف',
    'torrent_err_file_priorities': 'فشل تعديل أولويات الملفات',
    'torrent_err_speed_limits': 'فشل ضبط حدود السرعة',
    'torrent_err_rss_fetch': 'فشل جلب RSS',
    'torrent_err_rss_rule': 'فشل تشغيل قاعدة RSS',
    'torrent_add_sheet_title': 'إضافة تورنت',
    'torrent_magnet_label': 'magnet:?xt=urn:...',
    'torrent_paused_on_add': 'إيقاف مؤقت عند الإضافة',
    'torrent_sequential': 'تحميل تسلسلي (للبث المباشر)',
    'torrent_add_file_button': 'ملف .torrent',
    'torrent_add_magnet_button': 'إضافة Magnet',
    'magnet_invalid_prefix': 'الرابط يجب أن يبدأ بـ magnet:?',
    'torrent_pick_file_failed': 'فشل اختيار الملف: {e}',
    'torrent_path_dialog_title': 'مسار ملف ‎.torrent',
    'torrent_path_open': 'فتح',
    'torrent_path_hint': '/path/to/file.torrent',
    'torrent_engine_unsupported_short': 'محرك BitTorrent غير مدعوم على هذه المنصة.',
    'torrent_search_title': 'بحث التورنت',
    'torrent_added_to_list': 'أُضيف إلى قائمة التورنت',
    'torrent_no_results': 'لا نتائج بعد.',
    'torrent_tab_overview': 'عام',
    'torrent_tab_files': 'الملفات',
    'torrent_tab_trackers': 'المتتبّعات',
    'torrent_label_state': 'الحالة',
    'torrent_label_total': 'الحجم الكلي',
    'torrent_label_downloaded': 'تم التحميل',
    'torrent_label_uploaded': 'تم الرفع',
    'torrent_label_dl_speed': 'سرعة التحميل',
    'torrent_label_ul_speed': 'سرعة الرفع',
    'torrent_label_peers': 'الأقران/البذور',
    'torrent_label_eta': 'الوقت المتبقي',
    'torrent_label_file_count': 'عدد الملفات',
    'torrent_label_info_hash': 'معلومة الـ hash',
    'torrent_label_save_path': 'مسار الحفظ',
    'torrent_files_not_ready': 'قائمة الملفات غير متاحة بعد.',
    'torrent_prowlarr_config_title': 'إعدادات Prowlarr / Jackett',
    'torrent_trackers_coming_soon':
        'تفاصيل المتتبّعات (Trackers) ستتوفر في تحديث قادم.',
    'torrent_tracker_line': '{status} · بذر {s} · أقران {l}',
    'torrent_search_hint': 'ابحث في المتعقّبات...',
    'torrent_search_enable_toggle': 'تفعيل البحث',
    'torrent_search_disabled_title': 'بحث التورنت معطّل افتراضياً',
    'torrent_search_disabled_body':
        'لا نستضيف أي indexers — البحث عبر Prowlarr أو Jackett خاص بك. أنت المسؤول عن قانونية المحتوى.',
    'torrent_search_save': 'حفظ',

    'torrent_seeders_abbr': 'بذور',
    'torrent_leechers_abbr': 'تحميل',
    'torrent_history_magnet': 'تورنت: {prefix}',
    'torrent_history_file': 'ملف تورنت',

    'torrent_api_key': 'API Key',
    'torrent_base_url': 'Base URL',
    'torrent_base_url_hint': 'http://localhost:9696',

    // مصادقة — رسائل مزوّد الحالة
    'auth_password_recovery_ok': 'يمكنك الآن تعيين كلمة مرور جديدة',
    'auth_reset_email_sent': 'تم إرسال رابط استعادة كلمة المرور إلى بريدك الإلكتروني',
    'auth_fill_email_password': 'يرجى إدخال البريد الإلكتروني وكلمة المرور',
    'auth_password_min_length': 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
    'auth_confirmation_email_sent': 'تم إرسال رابط التأكيد إلى بريدك الإلكتروني',
    'auth_confirm_hint_windows':
        'افتح الرابط من بريدك — سيُفتح تطبيق دارك تلقائياً. إن ظهرت صفحة فارغة، اضغط «إعادة إرسال الرابط» أدناه.',
    'auth_resend_confirmation': 'إعادة إرسال رابط التأكيد',
    'auth_signup_check_inbox':
        'إن كان البريد جديداً فسيصلك رابط التأكيد. تحقق من البريد العشوائي (Spam).',
    'auth_confirm_site_url_fallback':
        'تم إرسال البريد عبر رابط الموقع الافتراضي. أضف com.darkdownloader://login-callback في Supabase → Redirect URLs لفتح التطبيق مباشرة.',
    'auth_err_redirect_not_allowed':
        'رابط إعادة التوجيه غير مسموح في Supabase. أضف: com.darkdownloader://login-callback',
    'auth_err_signup_disabled': 'التسجيل معطّل في إعدادات Supabase',
    'auth_signup_failed_generic': 'تعذر إنشاء الحساب. حاول مجدداً.',
    'auth_unexpected': 'خطأ غير متوقع، تحقق من اتصالك بالإنترنت',
    'auth_oauth_failed': 'فشل تسجيل الدخول عبر {name}',
    'auth_oauth_callback_failed':
        'تعذّر إكمال تسجيل الدخول من المتصفح. تأكد من أن رابط إعادة التوجيه في لوحة Supabase يطابق التطبيق ثم أعد المحاولة.',
    'auth_err_session_sync':
        'تم قبول البيانات لكن لم تُحمَّل الجلسة. أعد تشغيل التطبيق أو تحقق من التخزين المحلي.',

    'auth_enter_email': 'يرجى إدخال البريد الإلكتروني',
    'auth_reset_link_sent': 'تم إرسال رمز استعادة كلمة المرور إلى بريدك',
    'auth_code_verified': 'تم التحقق من الرمز بنجاح ✅',
    'auth_password_update_success': 'تم تحديث كلمة المرور بنجاح ✅',
    'auth_err_invalid_creds': 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
    'auth_err_email_not_confirmed': 'يرجى تأكيد بريدك الإلكتروني أولاً',
    'auth_err_user_exists': 'هذا البريد الإلكتروني مسجل بالفعل',
    'auth_err_rate_limit': 'محاولات كثيرة، انتظر قليلاً ثم حاول مجدداً',
    'auth_err_invalid_email': 'صيغة البريد الإلكتروني غير صحيحة',
    'auth_err_network': 'خطأ في الاتصال، تحقق من الإنترنت',
    'auth_sign_in_unavailable': 'الخدمة غير متاحة حالياً. تحقق من الاتصال.',
    'auth_err_auth_with_detail': 'حدث خطأ أثناء المصادقة: {detail}',
    'auth_err_integrity_failed':
        'فشل التحقق من سلامة التطبيق. قد تكون النسخة معدّلة.',

    // مدير التحميل
    'dm_permissions_required': 'الصلاحيات مطلوبة — فعّلها من الإعدادات',
    'dm_downloading_label': 'جاري التحميل... {size}',
    'dm_merging': 'جاري دمج الصوت والفيديو...',
    'dm_merge_audio_missing':
        'لم يُعثر على ملف الصوت بعد التحميل — أعد المحاولة أو اختر تنسيقاً يجمع الصورة والصوت.',
    'dm_merge_failed': 'فشل دمج الصوت مع الفيديو — {detail}',
    'dm_err_cancelled': 'تم الإلغاء',
    'dm_err_no_network': 'لا يوجد اتصال بالإنترنت',
    'dm_err_timeout': 'انتهت مهلة الاتصال',
    'dm_err_link_expired': 'الرابط منتهي الصلاحية — أعد الاستخراج',
    'dm_err_empty_file': 'الملف فارغ — مشكلة في الشبكة',
    'dm_err_storage_permission': 'يجب منح صلاحية التخزين',
    'dm_err_no_space': 'مساحة التخزين ممتلئة',
    'dm_err_http_client': 'الرابط غير متاح',
    'dm_err_http_server': 'الخادم يعاني حالياً — جرّب لاحقاً',
    'dm_err_http_forbidden': 'الخادم رفض الطلب أو انتهت صلاحية الجلسة — أعد تحليل الرابط.',
    'dm_err_http_not_found': 'المورد غير موجود على الخادم (404).',
    'dm_err_connection_lost': 'انقطع الاتصال أثناء التحميل — أعد المحاولة.',
    'dm_tab_active': 'النشطة',
    'dm_tab_completed': 'المكتملة',
    'dm_empty_active': 'لا توجد تحميلات نشطة',
    'dm_empty_completed': 'لا توجد تحميلات مكتملة بعد',
    'dm_preview': 'معاينة',
    'dm_share': 'مشاركة',
    'dm_open_folder': 'فتح المجلد',
    'dm_open_file': 'فتح الملف',
    'dm_retry': 'إعادة المحاولة',
    'dm_pause': 'إيقاف مؤقت',
    'dm_resume': 'استئناف',
    'dm_queued': 'في الانتظار',
    'dm_paused': 'متوقف مؤقتاً',
    'dm_file_missing': 'الملف غير موجود على الجهاز',
    'dm_open_folder_failed': 'تعذّر فتح المجلد',
    'home_browse_download_title': 'تصفح وحمّل',
    'home_browse_download_subtitle':
        'افتح المواقع داخل التطبيق — نكتشف الفيديو ونضيفه للطابور بضغطة',
    'browser_quick_download_page': 'تحميل الصفحة',
    'browser_detected_bar_title': '{count} فيديو جاهز للتحميل',
    'browser_detected_bar_subtitle': '{platform} — اضغط لعرض الكل',
    'dm_retry_all_failed': 'إعادة محاولة الفاشلة',
    'dm_pause_queue': 'إيقاف الطابور مؤقتاً',
    'dm_resume_queue': 'استئناف الطابور',
    'dm_queue_paused_banner': 'الطابور متوقف — لن تبدأ تحميلات جديدة حتى تضغط استئناف.',
    'dm_stop_active': 'إيقاف التحميلات الجارية',
    'downloads_tab_queue': 'قائمة التحميل',
    'downloads_tab_cloud': 'السجل السحابي',
    'browser_load_failed': 'تعذّر تحميل الصفحة',
    'browser_load_retry': 'إعادة المحاولة',
    'browser_win_err_timeout': 'انتهت مهلة الاتصال (WebView)',
    'browser_win_err_network': 'تعذّر الوصول للخادم أو الشبكة',
    'browser_win_err_generic': 'خطأ في المتصفح: {code}',
    'dm_auto_retrying': 'إعادة تلقائية بعد {s} ثانية (المحاولة {n}/3)',

    // FFmpeg
    'ffmpeg_err_video_missing': 'ملف الفيديو غير موجود',
    'ffmpeg_err_audio_missing': 'ملف الصوت غير موجود',
    'ffmpeg_err_source_missing': 'ملف المصدر غير موجود',
    'ffmpeg_merge_failed': 'تعذرت المعالجة النهائية للفيديو: {detail}',
    'ffmpeg_extract_failed': 'فشل استخراج الصوت: {detail}',
    'ffmpeg_remux_failed': 'فشل remux: {detail}',
    'ffmpeg_convert_failed': 'فشل التحويل: {detail}',
    'ffmpeg_trim_failed': 'فشل القص: {detail}',

    // إشعارات
    'notif_channel_downloads': 'التحميلات',
    'notif_channel_downloads_desc': 'تقدم التحميلات الجارية',
    'notif_download_complete': 'اكتمل التحميل',
    'notif_open_file': 'فتح الملف',
    'notif_download_failed_line': 'فشل التحميل: {title}',

    // دفع واشتراك
    'pay_premium_desc': 'وصول كامل لكل الميزات',
    'pay_premium_f1': 'تحميلات غير محدودة',
    'pay_premium_f2': 'جودة HD (حتى 1080p)',
    'pay_premium_f3': 'تحميل دفعات',
    'pay_premium_f4': 'بدون إعلانات',
    'pay_premium_f5': 'دعم فني',
    'pay_pro_desc': 'كل Premium + جودة 4K',
    'pay_pro_f1': 'كل ميزات Premium',
    'pay_pro_f2': 'جودة 4K',
    'pay_pro_f3': 'تحميل 3 ملفات معاً',
    'pay_pro_f4': 'تحرير متقدم',
    'pay_pro_f5': 'دعم أولوية',
    'pay_pro_f6': 'وصول API',
    'pay_fib_banner':
        'الدفع يتم عبر FIB عندما يكون متاحاً في منطقتك؛ غالباً بالدينار العراقي (IQD) حسب صفحة البنك. يجب أن يطابق المبلغ إعدادات الخادم.',
    'pay_err_login_required': 'يجب تسجيل الدخول أولاً',
    'pay_err_checkout_invalid_response': 'استجابة غير صالحة من خادم الدفع',
    'pay_err_checkout_status': 'فشل إنشاء جلسة الدفع (رمز {code})',
    'pay_err_checkout_network':
        'تعذر الاتصال بخادم الدفع. تحقق من الاتصال وحاول مجدداً.',
    'pay_err_cancel_generic': 'فشل إلغاء الاشتراك',
    'pay_err_cancel_network': 'تعذر إلغاء الاشتراك. حاول مجدداً.',
    'pay_err_checkout_create_failed': 'فشل إنشاء جلسة الدفع',
    'pay_err_fib_start_failed': 'تعذر بدء الدفع. يرجى المحاولة لاحقاً.',

    // مستخرج الفيديو
    'ext_err_no_streams': 'لم يتم العثور على روابط تحميل',
    'ext_err_network': 'تحقق من اتصالك بالإنترنت',
    'ext_err_timeout': 'انتهت مهلة الاتصال',
    'ext_err_login_required': 'الفيديو يتطلب تسجيل الدخول',
    'ext_err_not_available_region': 'الفيديو غير متاح في منطقتك',
    'ext_err_parse_failed':
        'فشل تحليل الرابط. تأكد من أن الرابط صحيح ومدعوم.',

    // تسجيل الدخول — واجهة
    'login_headline_signup': 'أنشئ حسابك الجديد',
    'login_subtitle_signin': 'مرحباً بك مجدداً في {app}',
    'login_subtitle_signup': 'انضم إلينا لتجربة تحميل غير محدودة',
    'login_full_name': 'الاسم الكامل',
    'login_val_name_required': 'يرجى إدخال الاسم',
    'login_reset_title': 'استعادة كلمة المرور',
    'login_reset_body': 'أدخل بريدك الإلكتروني وسنرسل لك رابط الاستعادة',
    'login_send': 'إرسال',
    'login_email_hint': 'example@email.com',
    'login_val_email_required': 'يرجى إدخال البريد الإلكتروني',
    'login_val_email_invalid': 'صيغة البريد الإلكتروني غير صحيحة',
    'login_val_password_required': 'يرجى إدخال كلمة المرور',
    'login_val_password_short': 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
    'login_continue_google': 'المتابعة عبر Google',
    'login_continue_apple': 'المتابعة عبر Apple',
    'login_check_email_title': 'تحقق من بريدك الإلكتروني',
    'login_check_email_prefix': 'أرسلنا رابط التأكيد إلى:',
    'login_check_email_hint':
        'افتح البريد الإلكتروني واضغط على الرابط لتفعيل حسابك، ثم ارجع وسجل دخولك.',
    'login_sign_in_action': 'تسجيل الدخول',
    'login_create_account': 'إنشاء حساب',
    'login_toggle_to_signin': 'لديك حساب بالفعل؟  ',
    'login_toggle_to_signup': 'ليس لديك حساب؟  ',
    'pro_welcome_title': 'أهلاً بك في عالم الاحتراف!',
    'pro_welcome_subtitle': 'تم تفعيل كافة ميزات PRO بنجاح. استمتع بتجربة تحميل لا حدود لها.',
    'pro_welcome_feature_1': 'تحميل فائق السرعة بدقة 8K',
    'pro_welcome_feature_2': 'تحميل قوائم التشغيل كاملة',
    'pro_welcome_feature_3': 'بدون إعلانات نهائياً',
    'pro_welcome_button': 'ابدأ الآن',
    'ui_lang_en': 'EN',
    'ui_lang_ar': 'ع',

    // إعدادات تحميل متقدمة
    'adv_settings_title': 'إعدادات متقدمة',
    'adv_parallel_connections': 'اتصالات متوازية',
    'adv_parallel_hint': 'أكثر اتصالات = أسرع تحميل (يستهلك RAM أكثر)',
    'adv_audio_format': 'صيغة الصوت النهائية',
    'adv_audio_format_hint': 'M4A أسرع (بدون ترميز). MP3 للتوافق. WAV/FLAC بدون ضغط.',
    'adv_codec_m4a': 'M4A (AAC)',
    'adv_codec_mp3': 'MP3',
    'adv_codec_opus': 'Opus',
    'adv_codec_wav': 'WAV',
    'adv_codec_flac': 'FLAC',

    'ffmpeg_kit_session_failed': 'فشلت عملية المعالجة النهائية',

    // FFmpeg سطح مكتب
    'ffmpeg_desktop_process_failed':
        'تعذّر تشغيل المحرك الأسطوري.\nيرجى التواصل مع الدعم الفني أو إعادة المحاولة.\n\n{detail}',
  };

  static const Map<String, String> en = {
    // General
    'app_name': 'Dark',
    'bootstrap_engine_failed_debug': 'Native engine failed to start.\n\n{detail}',
    'bootstrap_engine_failed_release': 'Native engine failed to start. Check logs or reinstall the app.',
    'profile_guest_name': 'Guest',
    'profile_seed_display_name': 'Dark user',
    'profile_no_email': 'Not signed in',
    'subscription_tier_free': 'Free',
    'profile_theme_color_title': 'App accent',
    'profile_theme_color_subtitle': 'Pick your preferred accent color',
    'profile_user_id_unknown': 'Unknown',
    'windows_url_protocol_desc': 'URL:{name} Protocol',
    'welcome': 'Welcome',
    'welcome_back': 'Welcome Back',
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    'failed': 'Failed',
    'cancel': 'Cancel',
    'save': 'Save',
    'delete': 'Delete',
    'edit': 'Edit',
    'retry': 'Retry',
    'close': 'Close',
    'confirm': 'Confirm',
    'privacy_policy': 'Privacy Policy',
    'terms_of_service': 'Terms of Service',
    'privacy_policy_content': 'Privacy Policy for Dark:\n\n1. Security: Your data is encrypted and protected with the latest technologies.\n2. Usage: Data is used only to improve the user experience and deliver our services.\n3. Privacy: Your files and privacy are our top priority.',
    'terms_of_service_content': 'Terms of Service for Dark:\n\n1. Subscription: PRO features require an active subscription.\n2. Refund Policy: As this is a digital service, refunds are not available once PRO features are activated or the first download begins.\n3. Fair Use: Use of the app to download copyrighted content without permission is prohibited.',
    'or': 'Or',
    'yes': 'Yes',
    'no': 'No',

    // Auth
    'login': 'Login',
    'signup': 'Sign Up',
    'logout': 'Logout',
    'email': 'Email',
    'password': 'Password',
    'create_account': 'Create Account',
    'already_have_account': 'Already have an account?',
    'no_account': "Don't have an account?",
    'forgot_password': 'Forgot password?',
    'reset_password': 'Reset Password',
    'confirm_logout': 'Do you want to logout?',

    // Navigation
    'home': 'Home',
    'downloads': 'Downloads',
    'profile': 'Profile',
    'browser': 'Browser',
    'settings': 'Settings',
    'search': 'Search',

    // Home
    'paste_url': 'Paste video URL here',
    'browse_web': 'Browse Websites',
    'enter_url': 'Enter video URL',
    'analyze': 'Analyze',
    'analyzing': 'Analyzing...',
    'suggested_link_title': 'Suggested link from clipboard',
    'supported_platforms': 'Supported Platforms',
    'quick_download': 'Quick Download',
    'bypass_blocks_label': 'Bypass Web Blocks',
    'bypass_blocks_hint': 'Use proxy servers to access blocked sites without VPN',
    'recent_downloads': 'Recent Downloads',
    'no_recent': 'No recent downloads',
    'see_all': 'See All',
    'tips': 'Tips',
    'tip_1': 'Paste any video link from supported platforms',
    'tip_2': 'Choose the quality before downloading',
    'tip_3': 'You can download audio only without video',

    // Download
    'download': 'Download',
    'downloading': 'Downloading',
    'download_complete': 'Download Complete',
    'download_failed': 'Download Failed',
    'add_to_queue': 'Add to Queue',
    'download_options': 'Download Options',
    'quality': 'Quality',
    'format': 'Format',
    'audio_only': 'Audio Only',
    'with_subtitles': 'With Subtitles',
    'file_size': 'File Size',
    'duration': 'Duration',
    'platform': 'Platform',
    'no_downloads': 'No active downloads',
    'clear_all': 'Clear All',
    'start_download': 'Start Download',
    'estimated_size': 'Estimated Size',
    'video_info': 'Video Info',
    'unsupported_platform': 'Platform not supported',
    'invalid_url': 'Invalid URL',
    'download_captured': 'Download Captured Video',
    'download_open_folder': 'Open file folder',
    'download_saved_in': 'Saved to',
    'download_file_missing_snack':
        'File not found at the saved path. Tap Open folder beside Play, or look inside the DarkDownloader folder in Downloads',
    'search_or_url': 'Search or enter URL',
    'videos_found': 'Videos discovered',
    'detected_videos': 'Detected Videos',
    'items': 'items',
    'browser_recent': 'Recent pages',
    'browser_copy_link': 'Copy current URL',
    'browser_open_external': 'Open in default browser',
    'browser_clear_history': 'Clear history',
    'browser_empty_history': 'No pages in history yet',
    'browser_new_tab': 'New tab',
    'browser_analyze_page': 'Analyze page for download',
    'browser_queue_best': 'Best quality → queue',
    'browser_choose_quality': 'Pick quality',
    'browser_incognito_mode': 'Incognito mode',
    'adblock_title': 'Ad-Blocker',
    'adblock_subtitle': 'Block ads and popups',
    'adblock_custom_rules': 'Custom Rules',
    'adblock_add_rule': 'Add Rule',
    'adblock_rule_hint': 'Example: ||ads.example.com^',
    'browser_queue_not_added':
        'Could not add to queue (permissions, subscription, or an active download for this video).',
    'browser_refresh': 'Refresh',
    'browser_desktop_site': 'Desktop site',
    'browser_mobile_site': 'Mobile site',
    'browser_clear_detected': 'Clear detected',
    'browser_link_copied': 'Link copied',
    'browser_no_url': 'No valid URL in the address bar',
    'browser_unsafe_url': 'Link not allowed (only http or https).',
    'browser_detected_subtitle': 'Media links are captured automatically on desktop',
    'browser_downloads_library': 'Download library',
    'browser_tabs': 'Tabs',
    'browser_more': 'More',
    'browser_tools': 'Browser tools',
    'browser_stop': 'Stop',
    'browser_extract_failed': 'Could not extract a video from this page',
    'browser_back': 'Back',
    'browser_forward': 'Forward',
    'browser_find_in_page': 'Find in page',
    'browser_find_hint': 'Type to search on this page',
    'browser_find_next': 'Next',
    'browser_find_close': 'Close',
    'browser_duplicate_tab': 'Duplicate tab',
    'browser_close_other_tabs': 'Close other tabs',
    'browser_share_link': 'Share link',
    'browser_whitelisted': 'Whitelisted (Ad-Blocker off)',
    'browser_add_to_whitelist': 'Add to whitelist',
    'pause': 'Pause',
    'resume': 'Resume',
    'browser_queue_all': 'Add all to queue (best quality)',
    'browser_queue_all_progress': 'Adding detected items…',
    'browser_queue_all_summary': 'Of {total}: added {added}, skipped {skipped}, failed {failed}',
    'browser_queue_all_step': '{current} / {total}',
    'browser_queue_all_cancel': 'Stop',
    'browser_queue_all_stopped': 'Stopped early: added {added}, skipped {skipped}, failed {failed} of {total}.',
    'bookmarks': 'Bookmarks',
    'browser_history_cloud_hint':
        'History stays on device; when signed in it merges with the cloud. Sync pulls and uploads your current list.',
    'browser_history_pull_cloud': 'Sync with cloud',
    'browser_sync_ok': 'Sync completed',
    'browser_sync_fail': 'Sync failed. Check Supabase table or your connection.',

    // Profile
    'my_profile': 'My Profile',
    'profile_display_name_fallback': 'User',
    'account_info': 'Account Info',
    'subscription_info': 'Subscription Info',
    'subscription': 'Subscription',
    'current_plan': 'Current Plan',
    'upgrade': 'Upgrade',
    'plan_free': 'Free',
    'plan_premium': 'Premium',
    'plan_pro': 'Pro',
    'active': 'Active',
    'inactive': 'Inactive',
    'expires': 'Expires',
    'total_downloads': 'Total Downloads',
    'about': 'About App',
    'language': 'Language',
    'floating_dl_title': 'Floating download button',
    'floating_dl_subtitle':
        'A small button on top of other apps. Copy the video link from your browser or social app, then tap to send it here. The OS does not allow injecting a button inside another app\'s video player.',
    'theme': 'Theme',
    'theme_follow_system': 'Use device setting',
    'dark_mode': 'Dark Mode',
    'light_mode': 'Light Mode',
    'arabic': 'العربية',
    'english': 'English',
    'profile_pick_accent': 'Pick accent color',
    'profile_upgrade_pro_title': 'Upgrade to PRO',
    'profile_upgrade_pro_subtitle': 'Higher speeds, unlimited downloads, and exclusive features',

    // Subscriptions
    'plans': 'Subscription Plans',
    'choose_plan': 'Choose Your Plan',
    'per_month': '/month',
    'popular': 'Most Popular',
    'cancel_subscription': 'Cancel Subscription',
    'confirm_cancel': 'Are you sure you want to cancel?',
    'select_plan': 'Select This Plan',
    'subscription_screen_title': 'Upgrade account',
    'subscription_headline': 'Choose your plan',
    'subscription_tagline':
        'Built for a global audience: upgrade to PRO via our secure payment partner (FIB) where the bank supports checkout.',
    'subscription_tier_premium': 'PREMIUM',
    'subscription_tier_pro': 'PRO',
    'subscription_price_premium': r'$9.99',
    'subscription_price_pro': r'$19.99',
    'subscription_period_slash_month': '/ mo',
    'subscription_local_payment': 'Pay with FIB (where available)',
    'subscription_pay_fib': 'Pay with FIB',
    'subscription_fib_sandbox_note':
        'For developers: sandbox host fib-stage.fib.iq; store FIB secrets in Supabase Edge Functions.',
    'subscription_subscribe_now': 'Subscribe now',
    'subscription_premium_f1': 'Unlimited downloads',
    'subscription_premium_f2': 'Up to 1080p (Full HD)',
    'subscription_premium_f3': 'No ads',
    'subscription_premium_f4': 'Email support',
    'subscription_pro_f1': 'Everything in Premium',
    'subscription_pro_f2': '4K Ultra HD quality',
    'subscription_pro_f3': 'Download 5 files at once',
    'subscription_pro_f4': 'Live chat support',
    'subscription_pro_f5': 'Priority access to new features',
    'trial_expired': 'Trial expired. Subscribe to continue.',
    'trial_remaining': 'Trial remaining: {h} hours',
    'subscribe_to_continue': 'Subscription required',
    'subscription_period_monthly': 'Monthly',
    'subscription_period_yearly': 'Yearly',
    'subscription_price_monthly': r'$1.5',
    'subscription_price_yearly': r'$15',

    // Messages
    'network_error': 'Network error, check your connection',
    'added_to_queue': 'Added to download queue',
    'playlist_preparing': 'Preparing playlist…',
    'playlist_added_batch': 'Added {n} items to the download queue',
    'playlist_nothing_enqueued': 'No items were added to the queue. Check the links or try again.',
    'playlist_download_selected': 'Download selected ({n})',
    'downloads_empty_local': 'No downloads in the queue',
    'cloud_history_empty': 'No cloud history yet',
    'cloud_history_load_error': 'Could not load history: {detail}',
    'history_kind_torrent': 'Type: torrent',
    'history_copied_magnet': 'Magnet link copied',
    'history_copied_video_url': 'Video URL copied',
    'dm_fallback_failed': 'Download failed',
    'dm_eta_remaining': 'Remaining: {eta}',
    'dm_move_queue_up': 'Move up in queue',
    'dm_move_queue_down': 'Move down in queue',
    'dm_schedule_section_title': 'Schedule download (e.g. overnight)',
    'dm_schedule_subtitle_now': 'Download immediately',
    'dm_schedule_subtitle_at': 'Starts at: {time}',
    'dm_schedule_toggle': 'Download at a set time',
    'dm_schedule_picker_help': 'Pick download start time',
    'removed_from_queue': 'Removed from queue',
    'copied': 'Copied',

    'confirm_clear_downloads':
        "Remove all downloads from this device's queue? This cannot be undone.",
    'generic_error_detail': 'Something went wrong: {detail}',

    'format_percent': '{p}%',
    /// Appended after a data amount for throughput (e.g. `12 MB/s`).
    'data_rate_suffix': '/s',

    'eta_under_minute': '{n}s',
    'eta_under_hour': '{m}m {s}s',
    'eta_under_day': '{h}h {m}m',
    'eta_days': '{d}d {h}h',

    // Quality picker — stream kinds
    'kind_muxed': 'Video + Audio',
    'kind_video_only': 'Video Only',
    'kind_audio_only': 'Audio Only',

    // Quality picker — filters
    'filter_resolution': 'Resolution',
    'filter_format': 'Format',
    'filter_kind': 'Type',
    'filter_all': 'All',
    'filter_video_with_audio': 'Video + audio',

    'merge_banner_title': 'Audio will be merged with video',
    'merge_banner_body':
        'This track needs a separate audio stream — the app will mux them automatically.',
    'merge_missing_audio': 'Pick an audio track to merge with the video',

    // Stream metadata
    'stream_codec_audio': 'Audio',
    'stream_codec_video': 'Video',
    'stream_codec_unknown': '—',
    'stream_bitrate_kbps': '{n} kbps',

    'platform_youtube': 'YouTube',
    'platform_tiktok': 'TikTok',
    'platform_instagram': 'Instagram',
    'platform_twitter': 'Twitter / X',
    'platform_facebook': 'Facebook',
    'platform_vimeo': 'Vimeo',
    'platform_dailymotion': 'Dailymotion',
    'platform_soundcloud': 'SoundCloud',
    'platform_reddit': 'Reddit',
    'platform_twitch': 'Twitch',
    'platform_pinterest': 'Pinterest',
    'platform_rumble': 'Rumble',

    'about_app_subtitle': '{name} v{version}',
    'about_legalese': '© {year} {name}',
    'company_info': 'Company info',
    'contact_us': 'Contact us',
    'contact_phone': 'Phone',
    'contact_whatsapp': 'WhatsApp',
    'contact_email': 'Email',
    'contact_website': 'Website',
    'contact_facebook': 'Facebook',
    'contact_instagram': 'Instagram',

    'codec': 'Codec',
    'bitrate': 'Bitrate',
    'fps': 'FPS',
    'resolution': 'Resolution',
    'container': 'Container',
    'selected_quality': 'Selected Quality',
    'best_quality': 'Best Quality',
    'no_streams_for_filter': 'No streams match the current filters',

    // Web
    'platform_banner_web_title': 'You are on the web build',
    'platform_banner_desktop_encoder_title': 'One-time encoder setup',
    'platform_banner_desktop_encoder_body':
        'Video/audio merge is unavailable: the legendary engine is temporarily not ready. Please tap Retry later.',
    'platform_banner_desktop_encoder_retry': 'Retry',
    'platform_banner_web_body':
        'Some features (e.g. BitTorrent) may be limited. For the full experience, use the desktop or Android app.',

    // Backend
    'backend_unavailable_title': 'Service unavailable',
    'backend_unavailable_body':
        'Cannot reach the server right now. Account sync and subscriptions are unavailable; direct downloads still work.',
    'backend_unavailable_login_title': 'Supabase is not configured',
    'backend_unavailable_login_lead':
        'Sign-in stays disabled until the app can read your project URL and anon key. Pick one setup path:',
    'backend_unavailable_login_opt_dart_define':
        'When running/building add:\n--dart-define=SUPABASE_URL=https://….supabase.co\n--dart-define=SUPABASE_ANON_KEY=…',
    'backend_unavailable_login_opt_file':
        'Or create supabase_local.json at the path below (UTF-8), then fully restart the app.',
    'backend_unavailable_login_path_label': 'File path',
    'backend_unavailable_login_open_folder': 'Open folder',
    'backend_unavailable_login_copy_path': 'Copy path',
    'backend_unavailable_login_view_example': 'View JSON example',
    'backend_unavailable_login_copied': 'Path copied',
    'backend_unavailable_login_restart':
        'After saving the file or changing defines, quit the app completely and launch again.',
    'backend_unavailable_login_release_local_disabled':
        'Release builds ignore supabase_local.json unless built with ALLOW_SUPABASE_LOCAL_FILE=true — use dart-define or baked-in store config.',
    'backend_unavailable_login_hint':
        'Supabase is not configured. Use the setup card above or pass dart-define when building.',

    // Torrents
    'magnet_added': 'Magnet link added',
    'torrent_label': 'Torrents',
    'torrent_title': 'Torrents',
    'torrent_engine_init_failed': 'Failed to initialize torrent engine:',
    'torrent_tab_active': 'Active ({n})',
    'torrent_tab_seeding': 'Seeding ({n})',
    'torrent_tab_completed': 'Completed ({n})',
    'torrent_tab_all': 'All',
    'torrent_search_tooltip': 'Search',
    'torrent_add_fab': 'Add torrent',
    'torrent_empty_filter': 'No torrents in this filter',
    'torrent_error': 'Error: {e}',
    'torrent_menu_pause': 'Pause',
    'torrent_menu_resume': 'Resume',
    'torrent_menu_remove': 'Remove from list',
    'torrent_menu_remove_with_files': 'Delete with files',
    'torrent_stats_line': 'Active {a} · seeding {s}',
    'home_torrent_unsupported': 'Torrents are not available on this device',
    'torrent_unsupported_title': 'BitTorrent is not available on this platform.',
    'torrent_unsupported_subtitle': 'Use Windows, macOS, Linux, or Android.',
    'torrent_err_add_magnet': 'Failed to add magnet',
    'torrent_err_add_torrent_file': 'Failed to add torrent file',
    'torrent_err_pause': 'Failed to pause',
    'torrent_err_resume': 'Failed to resume',
    'torrent_err_remove': 'Failed to remove',
    'torrent_err_file_priorities': 'Failed to update file priorities',
    'torrent_err_speed_limits': 'Failed to set speed limits',
    'torrent_err_rss_fetch': 'Failed to fetch RSS',
    'torrent_err_rss_rule': 'Failed to run RSS rule',
    'torrent_add_sheet_title': 'Add torrent',
    'torrent_magnet_label': 'magnet:?xt=urn:...',
    'torrent_paused_on_add': 'Add paused',
    'torrent_sequential': 'Sequential download (for streaming)',
    'torrent_add_file_button': '.torrent file',
    'torrent_add_magnet_button': 'Add magnet',
    'magnet_invalid_prefix': 'Link must start with magnet:?',
    'torrent_pick_file_failed': 'Could not pick file: {e}',
    'torrent_path_dialog_title': 'Path to .torrent file',
    'torrent_path_open': 'Open',
    'torrent_path_hint': '/path/to/file.torrent',
    'torrent_engine_unsupported_short': 'BitTorrent engine is not available on this platform.',
    'torrent_search_title': 'Torrent search',
    'torrent_added_to_list': 'Added to torrent list',
    'torrent_no_results': 'No results yet.',
    'torrent_tab_overview': 'Overview',
    'torrent_tab_files': 'Files',
    'torrent_tab_trackers': 'Trackers',
    'torrent_label_state': 'State',
    'torrent_label_total': 'Total size',
    'torrent_label_downloaded': 'Downloaded',
    'torrent_label_uploaded': 'Uploaded',
    'torrent_label_dl_speed': 'Download speed',
    'torrent_label_ul_speed': 'Upload speed',
    'torrent_label_peers': 'Peers / seeds',
    'torrent_label_eta': 'Time remaining',
    'torrent_label_file_count': 'File count',
    'torrent_label_info_hash': 'Info hash',
    'torrent_label_save_path': 'Save path',
    'torrent_files_not_ready': 'File list is not available yet.',
    'torrent_prowlarr_config_title': 'Prowlarr / Jackett settings',
    'torrent_trackers_coming_soon':
        'Full tracker details will arrive in a future update.',
    'torrent_tracker_line': '{status} · seeds {s} · leechers {l}',
    'torrent_search_hint': 'Search indexers...',
    'torrent_search_enable_toggle': 'Enable search',
    'torrent_search_disabled_title': 'Torrent search is off by default',
    'torrent_search_disabled_body':
        'We do not host indexers — search goes through your own Prowlarr or Jackett. You are responsible for the legality of content you search for.',
    'torrent_search_save': 'Save',
    'torrent_seeders_abbr': 'S',
    'torrent_leechers_abbr': 'L',
    'torrent_history_magnet': 'Torrent: {prefix}',
    'torrent_history_file': 'Torrent file',
    'torrent_api_key': 'API Key',
    'torrent_base_url': 'Base URL',
    'torrent_base_url_hint': 'http://localhost:9696',

    // Auth (provider messages)
    'auth_password_recovery_ok': 'You can now set a new password',
    'auth_reset_email_sent': 'A password recovery link has been sent to your email',
    'auth_fill_email_password': 'Please enter your email and password',
    'auth_password_min_length': 'Password must be at least 6 characters',
    'auth_confirmation_email_sent': 'A confirmation link was sent to your email',
    'auth_confirm_hint_windows':
        'Open the link from your email — Dark should launch automatically. If you see a blank page, tap Resend confirmation below.',
    'auth_resend_confirmation': 'Resend confirmation link',
    'auth_signup_check_inbox':
        'If this email is new, a confirmation link was sent. Check your spam folder.',
    'auth_confirm_site_url_fallback':
        'Email sent using the default site URL. Add com.darkdownloader://login-callback in Supabase Redirect URLs to open the app directly.',
    'auth_err_redirect_not_allowed':
        'Redirect URL is not allowed in Supabase. Add: com.darkdownloader://login-callback',
    'auth_err_signup_disabled': 'Sign-up is disabled in Supabase settings',
    'auth_signup_failed_generic': 'Could not create the account. Try again.',
    'auth_unexpected': 'Unexpected error — check your internet connection',
    'auth_oauth_failed': 'Sign-in with {name} failed',
    'auth_oauth_callback_failed':
        'Could not finish sign-in from the browser. Confirm the redirect URL in your Supabase dashboard matches this app, then try again.',
    'auth_err_session_sync':
        'Credentials were accepted but the session did not load. Restart the app or check local storage.',

    'auth_enter_email': 'Please enter your email',
    'auth_reset_link_sent': 'A password reset code has been sent to your email',
    'auth_code_verified': 'Code verified successfully ✅',
    'auth_password_update_success': 'Password updated successfully ✅',
    'auth_err_invalid_creds': 'Invalid email or password',
    'auth_err_email_not_confirmed': 'Please confirm your email first',
    'auth_err_user_exists': 'This email is already registered',
    'auth_err_rate_limit': 'Too many attempts. Wait a moment and try again',
    'auth_err_invalid_email': 'Invalid email format',
    'auth_err_network': 'Connection error — check the internet',
    'auth_sign_in_unavailable': 'Service unavailable. Check your connection.',
    'auth_err_auth_with_detail': 'Authentication error: {detail}',
    'auth_err_integrity_failed':
        'App integrity check failed. This build may have been modified.',

    // Download manager
    'dm_permissions_required':
        'Permissions required — enable them in system settings',
    'dm_downloading_label': 'Downloading... {size}',
    'dm_merging': 'Merging audio and video...',
    'dm_merge_audio_missing':
        'Audio file was not found after download — try again or pick a muxed format.',
    'dm_merge_failed': 'Could not mux audio into video — {detail}',
    'dm_err_cancelled': 'Cancelled',
    'dm_err_no_network': 'No internet connection',
    'dm_err_timeout': 'Connection timed out',
    'dm_err_link_expired': 'Link expired — extract again',
    'dm_err_empty_file': 'Empty file — possible network issue',
    'dm_err_storage_permission': 'Storage permission is required',
    'dm_err_no_space': 'Storage is full',
    'dm_err_http_client': 'Link is not available',
    'dm_err_http_server': 'Server is having issues — try again later',
    'dm_err_http_forbidden': 'The server denied the request or the session expired — extract again.',
    'dm_err_http_not_found': 'Resource not found on the server (404).',
    'dm_err_connection_lost': 'Connection dropped during download — try again.',
    'dm_tab_active': 'Active',
    'dm_tab_completed': 'Completed',
    'dm_empty_active': 'No active downloads',
    'dm_empty_completed': 'No completed downloads yet',
    'dm_preview': 'Preview',
    'dm_share': 'Share',
    'dm_open_folder': 'Open folder',
    'dm_open_file': 'Open file',
    'dm_retry': 'Retry',
    'dm_pause': 'Pause',
    'dm_resume': 'Resume',
    'dm_queued': 'Queued',
    'dm_paused': 'Paused',
    'dm_file_missing': 'File not found on device',
    'dm_open_folder_failed': 'Could not open folder',
    'home_browse_download_title': 'Browse & download',
    'home_browse_download_subtitle':
        'Open sites in-app — we detect video and queue it in one tap',
    'browser_quick_download_page': 'Download page',
    'browser_detected_bar_title': '{count} video(s) ready to download',
    'browser_detected_bar_subtitle': '{platform} — tap to see all',
    'dm_retry_all_failed': 'Retry failed downloads',
    'dm_pause_queue': 'Pause download queue',
    'dm_resume_queue': 'Resume queue',
    'dm_queue_paused_banner': 'Queue paused — new downloads will not start until you resume.',
    'dm_stop_active': 'Stop active downloads',
    'downloads_tab_queue': 'Active downloads',
    'downloads_tab_cloud': 'Cloud history',
    'browser_load_failed': 'Could not load page',
    'browser_load_retry': 'Retry',
    'browser_win_err_timeout': 'Connection timed out (WebView)',
    'browser_win_err_network': 'Could not reach the server or network',
    'browser_win_err_generic': 'Browser error: {code}',
    'dm_auto_retrying': 'Auto-retry in {s}s (attempt {n}/3)',

    // FFmpeg
    'ffmpeg_err_video_missing': 'Video file not found',
    'ffmpeg_err_audio_missing': 'Audio file not found',
    'ffmpeg_err_source_missing': 'Source file not found',
    'ffmpeg_merge_failed': 'Final processing failed: {detail}',
    'ffmpeg_extract_failed': 'Audio extract failed: {detail}',
    'ffmpeg_remux_failed': 'Remux failed: {detail}',
    'ffmpeg_convert_failed': 'Transcode failed: {detail}',
    'ffmpeg_trim_failed': 'Trim failed: {detail}',

    // Notifications
    'notif_channel_downloads': 'Downloads',
    'notif_channel_downloads_desc': 'Ongoing download progress',
    'notif_download_complete': 'Download complete',
    'notif_open_file': 'Open file',
    'notif_download_failed_line': 'Download failed: {title}',

    // Payments & subscription
    'pay_premium_desc': 'Full access to all features',
    'pay_premium_f1': 'Unlimited downloads',
    'pay_premium_f2': 'HD quality (up to 1080p)',
    'pay_premium_f3': 'Batch downloads',
    'pay_premium_f4': 'Ad-free',
    'pay_premium_f5': 'Support',
    'pay_pro_desc': 'Everything in Premium + 4K',
    'pay_pro_f1': 'All Premium features',
    'pay_pro_f2': '4K quality',
    'pay_pro_f3': 'Download 3 files at once',
    'pay_pro_f4': 'Advanced editing',
    'pay_pro_f5': 'Priority support',
    'pay_pro_f6': 'API access',
    'pay_fib_banner':
        'Payments are processed via FIB when available in your region; amounts are often in IQD on the bank checkout page and must match your server configuration.',
    'pay_err_login_required': 'You must sign in first',
    'pay_err_checkout_invalid_response': 'Invalid response from payment server',
    'pay_err_checkout_status': 'Could not create checkout session (code {code})',
    'pay_err_checkout_network':
        'Cannot reach the payment server. Check your connection and try again.',
    'pay_err_cancel_generic': 'Could not cancel subscription',
    'pay_err_cancel_network': 'Could not cancel subscription. Try again.',
    'pay_err_checkout_create_failed': 'Could not create checkout session',
    'pay_err_fib_start_failed': 'Could not start payment. Please try again later.',

    // Video extractor
    'ext_err_no_streams': 'No download links were found',
    'ext_err_network': 'Check your internet connection',
    'ext_err_timeout': 'Connection timed out',
    'ext_err_login_required': 'This video requires you to be signed in',
    'ext_err_not_available_region': 'This video is not available in your region',
    'ext_err_parse_failed':
        'Could not parse this link. Check that the URL is valid and supported.',

    // Login UI
    'login_headline_signup': 'Create your new account',
    'login_subtitle_signin': 'Welcome back to {app}',
    'login_subtitle_signup': 'Join us for unlimited downloads',
    'login_full_name': 'Full name',
    'login_val_name_required': 'Please enter your name',
    'login_reset_title': 'Reset password',
    'login_reset_body':
        'Enter your email and we will send you a recovery link',
    'login_send': 'Send',
    'login_email_hint': 'example@email.com',
    'login_val_email_required': 'Please enter your email',
    'login_val_email_invalid': 'Invalid email format',
    'login_val_password_required': 'Please enter your password',
    'login_val_password_short': 'Password must be at least 6 characters',
    'login_continue_google': 'Continue with Google',
    'login_continue_apple': 'Continue with Apple',
    'login_check_email_title': 'Check your email',
    'login_check_email_prefix': 'We sent a confirmation link to:',
    'login_check_email_hint':
        'Open your email, tap the link to activate your account, then return and sign in.',
    'login_sign_in_action': 'Sign in',
    'login_create_account': 'Create account',
    'login_toggle_to_signin': 'Already have an account?  ',
    'login_toggle_to_signup': "Don't have an account?  ",
    'pro_welcome_title': 'Welcome to the PRO Club!',
    'pro_welcome_subtitle': 'All PRO features have been successfully activated. Enjoy an unlimited downloading experience.',
    'pro_welcome_feature_1': '8K Ultra High-Speed Downloads',
    'pro_welcome_feature_2': 'Full Playlist Downloads',
    'pro_welcome_feature_3': 'Zero Ads, Forever',
    'pro_welcome_button': 'Get Started',
    'ui_lang_en': 'EN',
    'ui_lang_ar': 'ع',

    // Advanced download settings
    'adv_settings_title': 'Advanced settings',
    'adv_parallel_connections': 'Parallel connections',
    'adv_parallel_hint':
        'More connections = faster download (uses more RAM)',
    'adv_audio_format': 'Output audio format',
    'adv_audio_format_hint':
        'M4A is fastest (no re-encode). MP3 for compatibility. WAV/FLAC uncompressed.',
    'adv_codec_m4a': 'M4A (AAC)',
    'adv_codec_mp3': 'MP3',
    'adv_codec_opus': 'Opus',
    'adv_codec_wav': 'WAV',
    'adv_codec_flac': 'FLAC',

    'ffmpeg_kit_session_failed': 'Processing failed',

    // Desktop FFmpeg
    'ffmpeg_desktop_process_failed':
        'Could not run the Legendary Engine.\n'
        'Please contact support or try again later.\n\n'
        '{detail}',
  };

  static String translate(String key, Locale locale) {
    if (locale.languageCode == 'ar') return ar[key] ?? key;
    return en[key] ?? key;
  }
}

extension LocaleExtension on Locale {
  bool get isArabic => languageCode == 'ar';
  bool get isEnglish => languageCode == 'en';
}
