// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            // These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Blocker`


            void  rustInitAdblocker({required List<String> rules }) => RustLib.instance.api.crateApiAdblockEngineRustInitAdblocker(rules: rules);

bool  rustShouldBlockUrl({required String url }) => RustLib.instance.api.crateApiAdblockEngineRustShouldBlockUrl(url: url);

List<String>  rustGetDefaultAdRules() => RustLib.instance.api.crateApiAdblockEngineRustGetDefaultAdRules();

            
            