// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `_unpack_bypass`, `apply_decipher_ops`, `apply_js_transforms`, `apply_n_transform_to_url`, `browser_client_with_proxy`, `browser_client`, `classify_codec`, `decipher_signature`, `default_audio_codec_for`, `detect_platform`, `eval_captured`, `extract_balanced_braces`, `extract_dailymotion`, `extract_eporner`, `extract_facebook`, `extract_fn_body`, `extract_generic_recursive`, `extract_generic`, `extract_instagram_shortcode`, `extract_instagram`, `extract_json_value`, `extract_meta_property`, `extract_n_fn_as_global`, `extract_n_value`, `extract_player_js_url`, `extract_playlist`, `extract_reddit`, `extract_rumble`, `extract_soundcloud`, `extract_sts_from_player_js`, `extract_tiktok_id`, `extract_tiktok`, `extract_tweet_id`, `extract_twitch`, `extract_twitter`, `extract_via_invidious_with_retry`, `extract_via_invidious`, `extract_via_piped_with_retry`, `extract_via_piped`, `extract_vimeo`, `extract_youtube`, `extract_yt_initial_player_response`, `fetch_html_with_bypass`, `fetch_initial_player_response`, `fetch_player_js_path_from_embed`, `fetch_visitor_data`, `final_sort`, `find_visitor_data_in_json`, `get_regex`, `get_visitor_data`, `infer_width`, `inject_iife_capture`, `innertube_android_vr`, `innertube_android`, `innertube_ios`, `innertube_mweb`, `innertube_post`, `innertube_tv_embedded`, `innertube_web_embedded`, `load_player_functions`, `mk_audio_only_stream`, `mk_muxed_stream`, `mk_yt_stream`, `parse_bitrate_from_quality`, `parse_codecs_from_mime`, `parse_decipher_fn_name`, `parse_decipher_ops`, `parse_fps_from_quality`, `parse_height_from_quality`, `parse_mime_container`, `parse_n_fn_name`, `parse_youtube_id`, `player_cache`, `replace_n_value`, `resolve_stream_url`, `run_js_fn`, `stream_kind_priority`, `twitter_guest_token`, `visitor_cache`, `youtube_build_result`, `youtube_has_any_streams`, `youtube_has_cipher_streams`, `youtube_has_direct_urls`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CodecKind`, `DecipherOp`, `PlayerFunctions`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<ExtractionResult> extract({required String url}) =>
    RustLib.instance.api.crateApiExtractorExtract(url: url);

Future<VideoInfoResult> extractWithOptions({
  required String url,
  required bool bypassBlocks,
}) => RustLib.instance.api.crateApiExtractorExtractWithOptions(
  url: url,
  bypassBlocks: bypassBlocks,
);
