// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_cache_path`, `load_local_rules`, `registry`, `save_local_rules`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// تحديث القواعد من رابط خارجي (GitHub Gist مثلاً)
Future<void> rustSyncRemoteRules({required String url}) =>
    RustLib.instance.api.crateApiRemoteRulesRustSyncRemoteRules(url: url);

/// جلب قيمة قاعدة معينة لمنصة محددة
Future<String?> getRemotePattern({
  required String platform,
  required String key,
}) => RustLib.instance.api.crateApiRemoteRulesGetRemotePattern(
  platform: platform,
  key: key,
);

String rustGetRulesStatus() =>
    RustLib.instance.api.crateApiRemoteRulesRustGetRulesStatus();

class PlatformRule {
  final String platform;
  final int version;
  final Map<String, String> patterns;

  const PlatformRule({
    required this.platform,
    required this.version,
    required this.patterns,
  });

  @override
  int get hashCode => platform.hashCode ^ version.hashCode ^ patterns.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlatformRule &&
          runtimeType == other.runtimeType &&
          platform == other.platform &&
          version == other.version &&
          patterns == other.patterns;
}

class RulesRegistry {
  final List<PlatformRule> rules;
  final BigInt lastUpdated;

  const RulesRegistry({required this.rules, required this.lastUpdated});

  static Future<RulesRegistry> default_() =>
      RustLib.instance.api.crateApiRemoteRulesRulesRegistryDefault();

  @override
  int get hashCode => rules.hashCode ^ lastUpdated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RulesRegistry &&
          runtimeType == other.runtimeType &&
          rules == other.rules &&
          lastUpdated == other.lastUpdated;
}
