// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

void muxVideoAudio({
  required String videoPath,
  required String audioPath,
  required String outputPath,
  required String ffmpegPath,
}) => RustLib.instance.api.crateApiVideoProcessorMuxVideoAudio(
  videoPath: videoPath,
  audioPath: audioPath,
  outputPath: outputPath,
  ffmpegPath: ffmpegPath,
);

void extractAudio({
  required String videoPath,
  required String outputPath,
  required String ffmpegPath,
}) => RustLib.instance.api.crateApiVideoProcessorExtractAudio(
  videoPath: videoPath,
  outputPath: outputPath,
  ffmpegPath: ffmpegPath,
);

void convertToMp3({
  required String inputPath,
  required String outputPath,
  required String ffmpegPath,
}) => RustLib.instance.api.crateApiVideoProcessorConvertToMp3(
  inputPath: inputPath,
  outputPath: outputPath,
  ffmpegPath: ffmpegPath,
);

void compressVideo({
  required String inputPath,
  required String outputPath,
  required String ffmpegPath,
}) => RustLib.instance.api.crateApiVideoProcessorCompressVideo(
  inputPath: inputPath,
  outputPath: outputPath,
  ffmpegPath: ffmpegPath,
);
